### ISSUE TITLE
xray exams are slow chrome 57.*

### ISSUE THREAD

**Issue by rfscheidt** [cornerstonejs/cornerstone#108]
After upgrade of chrome 57, the render time of images are very high.

![wado](https://cloud.githubusercontent.com/assets/7602639/25018591/03ec450e-205e-11e7-8eb7-81d7e9b4cf60.jpeg)

Versions:
cornerstone - v0.9.0
cornerstoneTools - v0.6.2
cornerstoneMath - v0.1.1
cornerstone-wado-image-loader - v0.5.2
cornerstoneWebImageLoader - v0.4.3
dicom-parser - v1.0.2

**Comment by FilippiSilva** [comment]
In my viewer, being a page based on the [cornerstone demo](http://chafey.github.io/cornerstoneDemo/), my actions on the image with the tools wwwc, stack scroll ... generate this result

Render Time:125 ms
Image Type:JPEG
Image # 1/1

In my report platform with other libraries the result is amazingly slower

Render Time:2228 ms
Image Type:JPEG
Image # 1/1

In firefox the performance continues to be exemplary with averages of 0 to 5 ms

**Comment by swederik** [comment]
Thanks for the report! We will look into this.

**Comment by jasonklotzer** [comment]
@rfscheidt:

- Would you be able to tell us what version of chrome you upgraded from?
- Can you try the same test on the latest version of corrnerstone?
- Can you more specifically quantify the render time you're now seeing and the resolution of the MG that you're testing with?

**Comment by FilippiSilva** [comment]
1 - chrome version 56.0.2924.87 (64-bit);
2 - yes, same result;
3 - render time:
         old       -> 95ms
         current -> 290ms
     resolution: 1770x2370 pixels;

**Comment by jpambrun** [comment]
Commit 5604a3800e869b381c7b8f8b4095e64fd3771572 currently in master should have fixed this issue. The reverted commit improved performance in some cases, but reduced it in other. Another solution is on the way.

**Comment by FilippiSilva** [comment]
@jpambrun 

After your commit, an image with a resolution of 1770x2370 has a render time of 120ms and is working very well.

But we have an image with a resolution of 3540x4740 that is taking 480ms to render.

![wado 7](https://cloud.githubusercontent.com/assets/4635445/25863066/bde99292-34c0-11e7-8aea-5552f6f7275c.jpg)

**Comment by jpambrun** [comment]
From my experience, these performance issues usually have two possible causes:

1) some de-optimization in chrome due to a function becoming polymorphic, say storedPixelDataToCanvasImageData() is called on an Uint16 and a Int16 in the same session;

2) the min/max where not set correctly in the DICOM causing out of bounds lookup in the lut.

On my PC, I can apply the lut at a rate of 0.9 Mpix/ms, so your image should definitely be in the <50 ms range, not 480 ms.

I have already pushed an ugly hack for some cases of 1) in master.
I hope this helps.

**Comment by onluiz** [comment]
Same happening here. Version 58.0.3029.96.

**Comment by swederik** [comment]
I'm going to close this since I think it's been solved. If someone has a specific image which is causing rendering issues, please open a new ticket.
