### ISSUE TITLE
Possible bug to fit an image to window with non-square pixels.

### ISSUE THREAD

**Issue by JJavierPozo** [cornerstonejs/cornerstone#110]
If we have an image with non-square pixels, for example higher than wide, when executing the function fitToWindow calculates the correct scale to fit the image to the canvas, but then the function **calculateTransform** increases the horizontal (or vertical) scale according to The Pixel Spacing values. This causes the image to be larger than the canvas and is not full displayed.

For example for the following case:
- image: 
Pixel Spacing 0.545455\0.596847
Columns 888
Rows 733
- canvas:
width: 777
height: 874

The calculation of the scale to fit the window gives a value of 0.875, but later the function **calculateTransform** increases the value of the width according to rowspacing, multiplying it by 1.0942 (enabledElement.image.columnPixelSpacing / enabledElement.image.rowPixelSpacing), this provokes That the width of the image is greater than the width of the canvas, so the image does not fit.

Could the opposite be done? Instead of increasing the width reduce the height (or the width as appropriate), so the image would fit the window.

Attached are two images, one with the scale of 0.875 where it is seen that the image is larger than the window and another that reduces the scale (manually) to 0.8 where the image fits better.
![image 1](https://cloud.githubusercontent.com/assets/27722417/25119190/6d6f9e22-2419-11e7-945a-068d662e0f44.png)
![image 2](https://cloud.githubusercontent.com/assets/27722417/25119192/6f96867a-2419-11e7-803e-786584613899.png)

**Comment by swederik** [comment]
Thanks for the detailed report!

It's very possible there is a bug here, I haven't really looked into non-square pixels thoroughly.

**Comment by swederik** [comment]
Should have been fixed by https://github.com/cornerstonejs/cornerstone/pull/255
