### ISSUE TITLE
WebGL DICOM loader not loading on Android 

### ISSUE THREAD

**Issue by au84** [cornerstonejs/cornerstone#132]
Hi Chris - The WebGL version of the DICOM viewer is not loading on 

Android Version: Nugat OS 7.0
OS Build: NBD92G
Handset: Nexus 6
Chrome Version: 58.0.3029.83

see attached image. 

Cheers

![img_2332](https://user-images.githubusercontent.com/14296830/27014074-e9beaf3e-4f0e-11e7-8e19-c1fd5cfecf7c.JPG)

**Comment by dannyrb** [comment]
@swederik this works for me. Are you having issues? I have access to a mobile device testing service if we need to check this out. I imagine this could be an issue of "just what versions of Android do we support?"

**Comment by dannyrb** [comment]
This is an ancient issue. If you're still having issues with it, please let me know. FWIW, I am unable to reproduce this in any evergreen browser on emulated Android devices.
