### ISSUE TITLE
Angle Tool does not work properly

### ISSUE THREAD

**Issue by CornerstoneFan** [cornerstonejs/cornerstone#146]
Hello, 

I have noticed that sometimes angle measurement tool does not work correctly. After I am clicking on the left mouse button for two times (but do not hold it) it renders only one line and stops after that (check out the video) and I have to looking for the third point of the angle. Probability of this issue occuring is at least one of eight attemps. However, when I am holding the button it is always correct. 

I was tracking this issue and I found out, that this problem probably happens only when onMouseMove event is called after the first click, but user does not hold the button.  

![issue](https://user-images.githubusercontent.com/30316903/28416088-d265c43c-6d52-11e7-87bb-f1e8ef5b29d0.gif)

**Comment by swederik** [comment]
This is an issue on Cornerstone Tools. The general question is: should we remove the 'angle' tool in favour of the 'simpleAngle' tool.

**Comment by dannyrb** [comment]
This is an old issue, for a different repository. We've renamed the angle tools to reduce confusion in tools @ v3.
