### ISSUE TITLE
ES6 modules direct browser loading

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstone#156]
There are still two PRs open on this issue.

I have been working with these PRs for a few months one. They are all correct and can be merged safely.

These PRs give a big advantage when developing. You can directly follow the debugger into cornerstone code, set breakpoints etc. Also making changes does not require going through the webpack phase which dramatically speed up development.

I would appreciate it if these PRs can be merged. It is hard to keep on merging to the head (as I just did).

Outstanding are:

cornerstoneWADOImageLoader:
  https://github.com/chafey/cornerstoneWADOImageLoader/pull/104

CornerstoneTools:
  https://github.com/chafey/cornerstoneTools/pull/214

Please let me know what is the progression on this and if there is any way I can assist in this merge.

Once done I am happy to add instructions on working with direct loading ES6 modules.

Thank you !

**Comment by swederik** [comment]
Looks like Chrome 61 supports this. Maybe we could add some instructions for how to do this to the Wiki?

**Comment by kofifus** [comment]
great ! but before we do that there is still the issues of the files that need to be changed to allow import.

I am not experienced with webpack, is there a way for the src version to be the one that supports modules natively and for the build process to use the other (original one) when building ?

This will be the best soloution

**Comment by swederik** [comment]
This article (https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7) seems to provide some good advice. You can use nomodule to include a compiled version in addition to the module version.

**Comment by kofifus** [comment]
Thx!

I think the article does not answer the issue we have here of different modules referencing each other (ie cornerstoneTools using cornerstone etc). 

Also I'm not sure nomodule is a good idea, my experience is that directly loading ES6 modules is A much slower and B buggy - chrome occasionally crashes the tab especially when the development tools are open. I think released versions should always use the bundled code and vice versa. We need some mechanism to easily switch between production and development code. I do something like

```
<script>

function loadJS(jsFile, module) { document.write('<scr' + 'ipt type="' + (module ? 'module' : 'text/javascript') + '" src="' + jsFile + '?cb=' + ZFPversion + '"></scr' + 'ipt>'); }

var module=false;

if (module) {
	loadJS('myDevelCodeThatUsesImports.js', true);
} else {
	loadJS('cornerstone.min.js');
	loadJS('cornerstoneTools.min.js');
	loadJS('myBuildCode.min.js');
}
</script>

```

But this still leaves the issue of the build process itself doing the right thing.

I think we need to modify the webpack build process so that it uses the 'old' version of ie cornerstone-core.js. Either by modifying the file before and after building (ugly) or by using a different version of the file when building, however I don't know how to do that :(

Other issues

- legacy browser support, if we let go of bundling it means cornerstone will stop working in old browsers

- external code using cornerstone will need to be modified as well, that is any code that now relies on cornerstone exisiting in the global namespace will now need to be modified to import cornerstone

- the article mentions rollup.js which maybe worth examining

I think it is best to get more people involved in this discussion, are you aware of other contributors to cornerstone that knowledgeable about the build process and help ?

Thx
