### ISSUE TITLE
Cornerstone increases system memory usage - Please help

### ISSUE THREAD

**Issue by algates90** [cornerstonejs/cornerstone#157]
When I try to load 100s of Dicom files into my cornerstone viewer, Chrome crashes with increased memory usage. What could be the workaround ?

**Comment by algates90** [comment]
Any suggestions ?

**Comment by kofifus** [comment]
What format are they ? try loading jpeg 12bit instead of jpeg200 or raw dicoms, I've had no problem with hundreds of those.

But in general you probably looking at smarter caching where you unload not recently used images etc ...

**Comment by algates90** [comment]
They are raw dicoms. I have tried to unload each image after they are displayed, but still no improvements on the memory utilization. Could you please give me a small code snippet, how you have been handling to unload images, etc

**Comment by algates90** [comment]
![image](https://user-images.githubusercontent.com/30894700/29965741-23034de6-8f0f-11e7-88ba-a2853270d35f.png)

**Comment by kofifus** [comment]
Sorry as I said above I load dicom 12 bits so I don't have memory issue. Why not compress them first ?

Your problem is probably that the images are still loaded into cornerstone imageCache, you need to find out how to also remove them from there.

**Comment by ArunRagav** [comment]
[FIXED!!!] @algates90 even I had this issue, decache is not happening and browser used to crash.

**Comment by kofifus** [comment]
ArunRagav - what file/line you are referring to ? can you submit a PR ?

**Comment by algates90** [comment]
@ArunRagav decache() or purge() both doesnt help.

**Comment by ArunRagav** [comment]
@algates90  function decache(imagePromise, imageId) accepts deferred(promise) object doesn't accepts normal promiseobject. when you call decache method make sure that you are passing deferred promise object as parameter

**Comment by dannyrb** [comment]
It appears this issue stemmed from an API misunderstanding. If you're still experiencing this issue, please open a new PR and include a minimal reproduction/example.

FWIW, I am able to decache and purge successfully. I see a clear reduction in memory usage using the profiler and in Task Manager.
