### ISSUE TITLE
Webgl rendering have issue with garbage collector

### ISSUE THREAD

**Issue by doananhbao94** [cornerstonejs/cornerstone#167]
Hi sir, I have a question wanna ask you. When I use cornerstone webgl to rendering image. I see the garbage collector run too much CPU ticks like that:

![image](https://user-images.githubusercontent.com/23447711/30971537-609af3fa-a492-11e7-84d6-80ce45df0ba7.png)

Can you have some suggestion to improve my performance when rendering with webgl, Thanks a lot

**Comment by swederik** [comment]
Are you still experiencing this? Could you try again with the latest version?

**Comment by doananhbao94** [comment]
I will try it. Sorry for late feedback. 
Thank you very much
