### ISSUE TITLE
drawCompositeImage.syncedViewports = memory leak

### ISSUE THREAD

**Issue by adreyfus** [cornerstonejs/cornerstone#179]
In `drawCompositeImage.js`, `syncedViewports` is filled each time a layer is added, and is never cleaned.

**Comment by swederik** [comment]
Yep this is an issue. The relevant variable has changed to 'originalViewportScale', but the issue remains. I'll try to get that patched soon.

**Comment by swederik** [comment]
Should be fixed now. Thanks @Zaid-Safadi! and thanks @adreyfus for the report!
