### ISSUE TITLE
About whether there are plans to develop MPR or VR module problem

### ISSUE THREAD

**Issue by gjun-neusoft** [cornerstonejs/cornerstone#189]
I wonder whether cornerstone plan to develop Mpr or VR related functions and/or modules,or not? Thanks

**Comment by swederik** [comment]
Hi there,

MPR and (especially) VR are enormously complex features to build and support. Much of the development of the OHIF / Cornerstone libraries is being funded by grants and private corporate investments. At this time I am not aware of any funding sources that are willing to put up the substantial resources required to build these features.

For now I would suggest looking at AMI (https://github.com/FNNDSC/ami) and VTK-js (https://github.com/Kitware/vtk-js) if you want client-side MPR and volume rendering.

**Comment by cancan101** [comment]
from the FAQ:
>How do you envision this library supporting 3D functionality such as MPR, MIP and VR?
>This library would be responsible for displaying the rendered image to the user. The rendering of the 3D image would be done by some other library - perhaps on the server side. This library is purely 2D and has no knowledge of 3D image space. It will probably make sense to have several layers on top of this library to provide 3D functionality. For example, one layer that has a 3D viewport with properties such as transformation matrix, slice thickness, transfer function/LUT, segmentation masks, etc. And another 3D tools layer that provides various tools on top of the 3d viewport (rotate, zoom, segment, scroll, etc).
OHIF/Cornerstone is working with the 3DSlicer project to integrate the two. I also expect to implement client side MPR at some point as the browsers seem to be handling large memory much better.

**Comment by dannyrb** [comment]
There is some talk about supporting "plugins" to Cornerstone-Tools that include external libraries as dependencies. If we go that route, it's more likely you'll see a 3rd party add-on, or a loosely maintained plugin that does offer MPR support.

At this point, I would say it's fairly far off from happening.

**Comment by dannyrb** [comment]
I feel like the spirit of this question has been answered. If you want to collaborate on a plugin that accomplishes MPR or VR, I suggest reaching out to the Google Group.
