### ISSUE TITLE
Uncaught TypeError: a.external.$ is not a function

### ISSUE THREAD

**Issue by babymaychen** [cornerstonejs/cornerstone#199]
```
const element = document.getElementById('dicomImage');
cornerstone.enable(element);
```
This problem appeared when i use enable function

**Comment by swederik** [comment]
What version are you using?

In Cornerstone 2.0.0 and above, we no longer depend on jQuery. We no longer have the requirement for cornerstone.external.$ to be added anywhere. I don't see how this error could occur since those pieces have been removed.

**Comment by babymaychen** [comment]
Thank you! I use the version of 1.1.3, 2.0.0 solve the problem.
