### ISSUE TITLE
Avoid manipulating the DOM when enabling an element

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstone#200]
Certain front-end frameworks (e.g. React) don't like it when third-party libraries change the DOM directly. There are two instances of this that I know of, which we should address:

1. Cornerstone Core: When enabling an element, [we create a Canvas inside it](https://github.com/cornerstonejs/cornerstone/blob/master/src/enable.js#L46).

We should update this section of enable to first check if there is already a canvas inside, and if so, we should use that. We could ask developers to use a specific class name, for example (e.g. cornerstone-canvas) to ensure that we don't just erase their canvases. This would allow developers to pre-specify in their components that this canvas exists, and so Cornerstone won't be adding anything to the DOM.

2. Cornerstone Tools: When enabling / activating / using the Magnify tool, [we create a Canvas inside the enabled element](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/magnify.js#L178)

Same as above, we should allow developers to avoid this by adding some check for canvases with a specific class name (e.g. cornerstone-tools-magnify-canvas).

Thoughts? @dannyrb

**Comment by dannyrb** [comment]
@swederik Thanks for kicking off a milestone :+1:

**Comment by swederik** [comment]
Thanks @lscoder!
