### ISSUE TITLE
use of LUTs with WebGL

### ISSUE THREAD

**Issue by jdnarvaez** [cornerstonejs/cornerstone#203]
I could be wrong, but it seems like the rendering pipeline ignores the modality and VOI LUT sequences when rendering? Is this planned for implementation or just an open issue at the moment?

**Comment by swederik** [comment]
Hi Juan,

The Modality LUT and VOI LUT transformations are applied in the shader:

For Int16, that's here: https://github.com/cornerstonejs/cornerstone/blob/master/src/webgl/shaders/int16.js#L59

**Comment by jdnarvaez** [comment]
I figured I had missed something somewhere, thanks! I'll have a look through there.
