### ISSUE TITLE
Multi window   problem

### ISSUE THREAD

**Issue by zhuashaoweiwu** [cornerstonejs/cornerstone#205]
Hello, I am a novice of cornerstone. I would like to ask you to set up multiple windows. When the mouse slides, multiple windows will slide down a picture. What is the example? Or what kind of API can achieve this function? Thank you, like an example in the annex.

**Comment by zhuashaoweiwu** [comment]
![1](https://user-images.githubusercontent.com/23515321/34404852-0774a578-ebeb-11e7-8eac-4c76f6942d7c.jpg)
![2](https://user-images.githubusercontent.com/23515321/34404853-07a8321c-ebeb-11e7-83b0-589d3978181b.jpg)

**Comment by zhuashaoweiwu** [comment]
cornerstone

**Comment by zhuashaoweiwu** [comment]
Or a good suggestion, thank you.

**Comment by dannyrb** [comment]
Have you looked at the different examples of additional functionality provided by [CornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools)? You can read more about the functionality it adds on top of cornerstone in these places:

- [Live Examples](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/index.html)
- [tools.cornerstonejs.org (new documentation)](https://tools.cornerstonejs.org/)
- [[Legacy] CornerstoneTools Wiki](https://github.com/cornerstonejs/cornerstoneTools/wiki)

I believe the functionality you're asking about can be found here:
- [Stack Image Position Offset Synchronizer](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackImagePositionOffsetSynchronizer/index.html)
- [Stack Scroll Snychronizer](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackScrollSynchronizer/index.html)

There are other synchronizers implemented that may also be worth taking a peak at:
- [Stack Image Index Snychronizer](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackImageIndexSynchronizer/index.html)
- [Stack Image Position Synchronizer](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackImagePositionSynchronizer/index.html)
- [Pan + Zoom Image Snychronizer](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/panZoomSynchronizer/index.html)

**Comment by zhuashaoweiwu** [comment]
thank you.

**Comment by dannyrb** [comment]
It looks like I answered your question! Thanks for reaching out. Please don't hesitate to request new features, request new documentation, and/or create a pull request to change something (:
