### ISSUE TITLE
simpleAngle  Click events 

### ISSUE THREAD

**Issue by zhuashaoweiwu** [cornerstonejs/cornerstone#208]
simpleAngle.activate(element, 1);

I want to click on this mark on the page to have an event. What should this do? Who can help me.

**Comment by dannyrb** [comment]
We do a pretty good job of watching for issues across all cornerstoneJS repositories, so there's no need to keep the same question open in multiple repositories. I'll close this one, and respond to your question here:

https://github.com/cornerstonejs/cornerstoneTools/issues/319#issuecomment-354726397
