### ISSUE TITLE
Label Maps with transparent background

### ISSUE THREAD

**Issue by SuguiSu** [cornerstonejs/cornerstone#214]
Is there a way to load a label map, but setting a transparent background? I would like to achieve a similar effect as with brush tool, but for a custom label map.

Thank you in advance!

**Comment by dannyrb** [comment]
Hi SuguiSu,

Thanks for the question! Could you provide a more detailed explanation of the functionality you'd like to see? Or maybe even a quick sketch/mock/picture of the functionality from a different program, or even in a program like Window's paint?

When I hear "label map", I have a few different conflicting ideas come to mind of what you _could mean_, but I'd like to know for sure before digging in.

Also, I think this question may make more sense over in [cornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools).

**Comment by swederik** [comment]
If you use an image / layer that is marked as rgba: true, you can use any RGBA color for any label map image and it should display fine. Note that by default, I believe rgba is false. Other than that, you just need to make the alpha value zero for the label you want to be invisible.

In this example, the value of 255 is the alpha channel: https://github.com/cornerstonejs/cornerstone/blob/master/example/falseColorMapping/index.html#L170

Just play with that last number and you should see the alpha level change for that label.

**Comment by SuguiSu** [comment]
Thank you, now everything is showing properly.
