### ISSUE TITLE
NPM build error - missing script: doc:generate

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstone#224]
I know that this is a minor bug, but [package.json](https://github.com/cornerstonejs/cornerstone/blob/master/package.json#L32) tries to call `doc:generate` which does not exist and throws an error during `npm run build`. Can we just delete this or will it be used in the future?

**Comment by dannyrb** [comment]
I'm not sure why we would want to generate docs on every `npm run build`. @swederik is this a holdover from recent updates to auto-generate API docs to add to our GitBook?

**Comment by swederik** [comment]
Yes I think this must be the jsdoc command we were using previously. I think we can safely remove it.
