### ISSUE TITLE
Maximum intensity projection

### ISSUE THREAD

**Issue by amitpanwar123** [cornerstonejs/cornerstone#228]
I want to incorporate this tool as it is required while 3D volume rendering of CT/MRI images to study the Angiographic procedures of the patient .

**Comment by dannyrb** [comment]
This may be a better issue for the `cornerstoneTools` project.

- Do you imagine a tool that allows you to specify a MIP thickness/range?
- Would it create a new stack of images depending on your thickness?

We don't currently have any tools that create "new" images, but it's certainly possible. This sounds like a fun one to make, but I'm not aware of how other viewer's implement. I'd be curious to see how/where you specify some of the settings that enable/disable the tool, and how you'd modify the slab thickness.

FWIW, (and for other non-radiologists) I found this video helpful in understanding [Maximum Intensity Projection (MIP)](https://www.youtube.com/watch?v=Qmdl0zckFnw)

**Comment by dannyrb** [comment]
Functionality like MIP is loosely slated in the `cornerstoneTools` repository as we work toward `vtk.js` viewport support/integration.
