### ISSUE TITLE
List all events in events.js

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstone#231]
It would be nice to have all Cornerstone events (and used throughout the library) as constants in `events.js` ([like CornerstoneTools does](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/events.js)).

**Comment by dannyrb** [comment]
I agree :+1:

- Adds clarity
- "One place" to update events

This largely happened in CornerstoneTools to make a refactor that changed event names easier (part of the "dropping jQuery" PR).

**Comment by ASVBPREAUBV** [comment]
TLDR: [events.js](https://github.com/cornerstonejs/cornerstone/blob/master/src/events.js)
