### ISSUE TITLE
Delete cornerstone.css in examples

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstone#232]
The examples in `cornerstone` and `cornerstoneTools` use a CSS file [`cornerstone.css`](https://github.com/cornerstonejs/cornerstone/blob/master/example/cornerstone.css) resp. [`cornerstone.min.css`](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/bootstrap.min.css). This makes the examples a bit untransparent and is also redundant with what the mentioned `pauseEvent` function in [Issue #351 of CornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools/issues/351) does. It is also often not necessary for the examples as most examples don't use an overlay, and is also not part of the main distribution as the name implies. Why not let us delete this file and add that CSS stuff to the example that really needs it (the overlay example). I can create a pull request if you agree.

**Comment by swederik** [comment]
Yeah that makes sense. I would like the examples to be as simple as possible.

**Comment by medihack** [comment]
@dannyrb Assign to me please as I am already reworking the examples a bit.
