### ISSUE TITLE
Keep dist files out of repository

### ISSUE THREAD

**Issue by medihack** [cornerstonejs/cornerstone#239]
@swederik I think you made a good point in #236 about the problem with checking in dist files in the repository and the thereby resulting merge conflicts. Let's discuss this a bit in its own issue here. What do you mean by "people using NPM may depend on dist/whatever being present"? It surely must be present when publishing the package to NPM, but it could be built when publishing it (this is for example how jQuery does it, at least it seems so looking at their repo). Or do you mean when people directly install the package from Github?

**Comment by dannyrb** [comment]
@medihack I let on that my company was doing something goofy with cornerstone's `npm` package when I last spoke to @swederik in our maintainer's Slack Channel<sup>1</sup>. But that doesn't matter, your approach is the right approach and would alleviate a lot of pain. I found some good insights at these URLs that we could turn into a checklist for updating our process:

- https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600
- https://docs.npmjs.com/misc/scripts

> The source, maybe assets, the bundled files etc. It’s not smart to include all of this into your npm package. It’s a good practice to keep the size small.
>
> First of all, you don’t want your generated files in your git repo. So you ignore them in your `.gitignore`
>
> You can also add a` .npmignore`.
>
> If you don’t create a `.npmignore` but you have a `.gitignore` npm will exlcude all files defined in the `.gitignore`

I'd be interested to hear your thoughts on their approach. I agree that getting our built files out of the repo would make managing PRs/contributions much easier 👍 

<hr />
<sup>1</sup> - Which if any contributor wants an invite to, just shoot me your e-mail address (danny.ri.brown@gmail.com)

**Comment by swederik** [comment]
Thanks @medihack for doing the research on this! The first approach does indeed sound like the easiest. I don't really see a big problem with removing the built files from dist as long as people that install it via NPM have it.

Anyone cloning the repository can just run the build. We can add built versions to tagged releases and provide the unpkg link as well. We would have to switch the examples to use unpkg (or native es6 modules with unpkg as a fallback?) or something similar.

**Comment by medihack** [comment]
@swederik Linking the CDN version in the examples is a good idea, especially as the other Cornerstone libraries use a bundled (not up-to-date) version of Cornerstone in their examples (e.g. [CornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools/blob/master/examples/cornerstone.js)) that could also be replaced by an always up-to-date CDN one.

**Comment by medihack** [comment]
@swederik A disadvantage (that just came to my mind) of using only the CDN links in the examples would be that the changes couldn't be tested right away (before publishing to NPM) in the examples. And that is a deal breaker :-( So using CDNs for external dependencies would be very good (like a CDN of the Cornerstone library in CornerstoneTools), but not the main library in the example itself.

**Comment by dannyrb** [comment]
@medihack does that change if we add a `@next` tag for releases? IE. You can specify the `@next` tag in the CDN url to _always_ have the most up-to-date code applied; not necessarily the most recent stable release?

**Comment by medihack** [comment]
@dannyrb The problem is more from a developer perspective. After I add some new code (or change something) I run 'yarn run build' and check if all tests still succeed. After that, I click through the examples and watch the console if all examples still work. If all this is ok, I am fine to push to git and create a pull request. When using CDNs in the examples I am not able to test the examples anymore as the code changes are not present there. So this is completely independent of a `@next` tag and not up-to-date code in the repository, or did I misunderstood your question somehow?

**Comment by dannyrb** [comment]
Ahh. Maybe that's not the best way? While checking the various live examples is a good gut check that nothing major is wrong, I think everything should be testable with a combination of automated unit tests and e2e tests.

If you find yourself rebuilding and manually looking at live examples, there's a good chance we're missing a test.

What I was originally getting at was that we should split create a new branch for our repositories for pre-releases (instead of having `master` be much further ahead of our current NPM release). `master` would continue to use the CDN links for pulling in latest releases, but a new `prerelease` branch would reference the up-to-date CDN source for an NPM package tagged with `@next`.

I hope that makes sense. Let me know if I'm missing the mark.

**Comment by medihack** [comment]
@dannyrb Of course, I absolutely agree. Testing is the way to go. But as the test quality could be improved (I am already thinking about how to improve the test situation of CornerstoneTools), the examples are a good additional verifier that everything still works. I also really like the convenience to simply try out new ideas by changing some code, running a rebuilt and looking how the example has changed. On the other hand, I could write a simple script that exchanges the CDN links for local links to the dist file.

And I also absolutely agree to have a `@next` branch, especially for breaking changes :-)

**Comment by dannyrb** [comment]
@medihack you're 100% right, haha. The examples are more or less a necessity until we get some good tests in place. I just want to make sure we don't inadvertently set things up so that there existence causes tests to be delayed/not written.

> On the other hand, I could write a simple script that exchanges the CDN links for local links to the dist file.

Hmm.. I wonder if there is a good/clean way we can do this that can make its way into the repo. I think that would be really handy.

> And I also absolutely agree to have a @next branch, especially for breaking changes :-)

I think I have @swederik bought into it now as well. Just need to make sure we're on the same page before I put it into affect for `cornerstone-tools` as it changes which branches we merge into and when.

**Comment by dannyrb** [comment]
This should be done :+1:
It should be easier to PR changes without worrying about the dist. You'll notice the difference in `node_modules` if you `npm install --save cornerstone-core@next`. The changes will make their way to `@latest` whenever we get around to creating the next stable release.

I'll be implementing a similar change to our other repositories. Thanks again for the suggestion and research, @medihack!
