### ISSUE TITLE
Update to Webpack 4

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstone#240]
I just tried to upgrade to Webpack 4, but it seems to be broken by something like this issue: https://github.com/webpack/webpack/issues/6634

If anyone wants to dig into this, feel free. I have a branch [here](https://github.com/cornerstonejs/cornerstone/tree/webpack4) to start from.

Basically the problem seems to be that the devtool: 'source-map' setting conflicts with library configuration as an object.

**Comment by swederik** [comment]
Sent a PR to Webpack to fix the issue: https://github.com/webpack/webpack/pull/6844
Once that's integrated, we can update our package.json and switch to Webpack 4.

**Comment by galelis** [comment]
This issue is now completed. 
PR is now merged.
https://github.com/cornerstonejs/cornerstone/pull/248
