### ISSUE TITLE
Switch to eventProxy may have broken some things

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/cornerstone#241]
We renamed cornerstone.events to cornerstone.eventProxy and it looks like some things didn't get updated:

https://github.com/cornerstonejs/cornerstone/blob/961a4ffd7a4045c1395e43d2e6538a22d9bc33be/example/eventhandling/index.html

**Comment by dannyrb** [comment]
@swederik can we revert that commit for now until we get things sorted? Shouldn't be a huge deal, as the change was not part of an NPM release.

**Comment by medihack** [comment]
@swederik @dannyrb Let me figure this out and make a pull request (just need 4 hours or so). Shouldn't be too complicated.
