### ISSUE TITLE
Image Cache: option to set minimum free cache on purge

### ISSUE THREAD

**Issue by vaibhav2383** [cornerstonejs/cornerstone#247]
In the current functionality, cache is purged if it grows beyond the maximum size defined. 
In a typical scenario, it results into very few images being removed (only 1 in most cases). This results into purge happening on every new image added to cache (once we hit the full mark).

**Suggestion**: Add another parameter _minFreeCacheOnPurge_ which drives how much cache must be freed up when purge is activated.

**Comment by mtjvankuik** [comment]
I would like to give this one a try! Also I was wondering whether or not the statement in which you mention that _cache is purged if it grows beyond the maximum size defined_ is currently the case. When I try to set **Maximum Cache Size** to 1000000 and start adding images, the parameter **Current Cache Size** value is not changed to 0 when there is insufficient cache left to add a new image.

**Comment by vaibhav2383** [comment]
1. **Current Cache Size** (_cacheSizeInBytes_) refers to the current "filled" size of cache and not empty.
2. The parameter can be added to _setMaximumSizeBytes_ function call with a default value set in _imageCache.js_ (say 25%). So if we hit the full mark on cache we will purge x% of cache rather that only going bare minimum. (See the purge code below)

```
  while (cacheSizeInBytes > maximumSizeInBytes) {
    const lastCachedImage = cachedImages[cachedImages.length - 1];
    const imageId = lastCachedImage.imageId;

    removeImageLoadObject(imageId);

    triggerEvent(events, 'cornerstoneimagecachepromiseremoved', { imageId });
  }
```

**Comment by swederik** [comment]
Interesting idea...

I don't have any issue with this new functionality as long as the default value for minFreeCacheOnPurgeInBytes is 0, so that the current behaviour is not changed. It would be great if you could make a PR with tests to ensure the functionality is working as expected.

**Comment by dannyrb** [comment]
This has been sitting around for over a year without moving. If someone would like to spike this, feel free to create a new issue/PR.

**Comment by Ashd15** [comment]
how i can implement cache management my website is crashing i am using this version @cornerstonejs/core@1.81.2
├─┬ @cornerstonejs/dicom-image-loader@1.81.2
│ ├── @cornerstonejs/core@1.81.2 deduped
│ └── dicom-parser@1.8.21 deduped
├─┬ @cornerstonejs/streaming-image-volume-loader@1.81.2
│ └── @cornerstonejs/core@1.81.2 deduped
├─┬ @cornerstonejs/tools@1.81.2
│ └── @cornerstonejs/core@1.81.2 deduped
├─┬ cornerstone-wado-image-loader@4.13.2 extraneous  
│ └── dicom-parser@1.8.21 deduped
└── dicom-parser@1.8.21

**Comment by Ashd15** [comment]
please help me

**Comment by No-Dream-No-Life** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，邮件我已收到，我将在看到后第一时间给您回复。
