### ISSUE TITLE
IHE Displayed Area Test cases 

### ISSUE THREAD

**Issue by Zaid-Safadi** [cornerstonejs/cornerstone#249]
This issue is to support the "Displayed Area" of the IHE Consistent Presentation of Images. 
MESA/IHE Spec: http://ihewiki.wustl.edu/wiki/index.php/MESA/Image_Display#Image_Display_Test_521:_Consistent_Presentation_of_Images
Test Case Resource: 
http://ihedoc.wustl.edu/mesasoftware/12.x/display_consistency/index.html

Originally, this is posted  by @jdnarvaez in [this PR](https://github.com/cornerstonejs/cornerstone/pull/211)

In order to test the changes, I've created a ["displayedArea" example](https://github.com/cornerstonejs/cornerstone/commits/displayed-area) (currently in the 'displayed-area' branch) to compare the results to the IHE test case.

## Current Behavior
Loading the first two IHE test cases "DISA_P01" and "DISA_P02" is not displaying the SMPTE image in Full  Screen mode

## Expected Behavior
Loading the images according to the displayed area parameters should show the SMPTE loaded in Full Screen

![display-area-example](https://user-images.githubusercontent.com/10813109/38175689-799524cc-35ae-11e8-9252-ddd1323b6fc4.PNG)

**Comment by jdnarvaez** [comment]
I believe the reason those do not work is because they are Presentation State test cases. You have to read in and apply an accompanying DICOM presentation state for them to display correctly.

![screen shot 2018-04-02 at 10 25 07 am](https://user-images.githubusercontent.com/3358381/38202093-293c2cc0-3660-11e8-8757-98dd546191a8.png)
![screen shot 2018-04-02 at 10 24 54 am](https://user-images.githubusercontent.com/3358381/38202094-294ce678-3660-11e8-8e1c-89cc053aa738.png)

**Comment by jdnarvaez** [comment]
For reference, icons generated by a standard icon server (without the presentation state applied) look like this:

![screen shot 2018-04-02 at 10 25 55 am](https://user-images.githubusercontent.com/3358381/38202140-4e25ff98-3660-11e8-9466-54b65428fa4d.png)

**Comment by Zaid-Safadi** [comment]
@jdnarvaez I am confused now. So, the presentation state information that comes with these images is what's being applied into the [viewport.dsplayedArea in the example](https://github.com/cornerstonejs/cornerstone/blob/displayed-area/example/displayedArea/index.html#L131), you can see these information in the [JSON file "testCase" property](https://github.com/cornerstonejs/cornerstone/blob/displayed-area/example/displayedArea/test-cases/DISA_P01.json#L17)

Do you see any issues with these values?

**Comment by Zaid-Safadi** [comment]
I believe I've finally have all 3 modes "SCALE TO FIT", "TRUE SIZE" and "MAGNIFY" displaying properly and will appreciate a second set of eyes to confirm if my understanding is correct for this feature!

So, for "TRUE SIZE" and "MAGNIFY", this is simply reading the values of the row/col pixel spacing and applying them as the width/height scale factor when calculating the transform. I believe the difference is by how the user (e.g. WADOLoader) should read  the DICOM tags and apply them to the row/col pixel spacing. For example, in the MAGNIFY case, you need to read the "Presentation Pixel Magnification Ratio" and apply (multiply) it to the row/col pixel spacing before passing to the displayedArea in Cornerstone.

For the "SCALE TO FIT", the code calculates the new scale factor from the true "Width/Height" of the image (based on the row/col spacing) then apply the Aspect Ratio to the scale factor.

The transformation for these cases can is all in the [**calculateTransform.js**](https://github.com/cornerstonejs/cornerstone/blob/1e86cbc3b2516244013c8a7d95b1ff7753973037/src/internal/calculateTransform.js#L32-L51)

I have updated the example now to include all 5 test cases from IHE and they seem to render correctly. However, I still need to clean the code and may do some refactoring once all is working as expected.
Also, there seems to be some extra line appearing at the bottom in the first test case referenced image box which needs to be fixed. 

![display-area-example02](https://user-images.githubusercontent.com/10813109/38287592-8119ef4c-3799-11e8-997a-08be80f81ade.PNG)

@jdnarvaez, thank you for your contribution to add this feature and hopefully you can help confirm the results and implementation such that we can get this incorporated and closed.

**Comment by jdnarvaez** [comment]
FWIW at first glance that seems to be correct to me. I’ll do my best to have a look at this in the next day or so.

**Comment by swederik** [comment]
@Zaid-Safadi That extra line at the bottom appears in Osirix as well. I wonder if it's in the pixel data?

**Comment by Zaid-Safadi** [comment]
I’ve checked the image in an older version of cornerstone and the line was still there. It only appears in specific zoom level so this is why it’s confusing but yes I can see it in other viewers (not all!)

**Comment by Zaid-Safadi** [comment]
This has been completed, merged into master and included in release 2.2.0
