### ISSUE TITLE
How to clear image/canvas for re-rendering the image?

### ISSUE THREAD

**Issue by govi20** [cornerstonejs/cornerstone#260]
I am loading the image using cornerstone in canvas. I have a button to clear the image loaded in canvas. I have tried following approaches to clear the canvas.

**Approach 1:**
```
context.save();
context.setTransform(1, 0, 0, 1, 0, 0);
context.clearRect(0, 0, canvas.width, canvas.height);
context.restore();
```
**Approach 2**
Remove previous canvas element and adding new canvas element to canvas back.

In both the approaches old image is getting cleared but new image is not rendering.

**Comment by Zaid-Safadi** [comment]
Hey @govi20, can you try calling disable on the element?

`cornerstone.disable(element);`

You can check this example:
https://github.com/cornerstonejs/cornerstone/blob/master/example/displayedArea/index.html#L135-L152

**Comment by mingBee** [comment]
disable bug you can check #618
