### ISSUE TITLE
2.2.0 breaks something in cornerstone-tools

### ISSUE THREAD

**Issue by fcortes** [cornerstonejs/cornerstone#262]
I'm not sure what it is exactly but cornerstone@2.2.0 breaks some cornerstone-tools@2.3.1 functionalities.
When loading a dicom image using the cornerstoneWADOImageLoader or the cornerstoneWebImageLoader it won't enable panning or zooming.
I built a small codepen showing the problem [here](https://codepen.io/anon/pen/odvVML)

The problem does not seem to happen when using cornerstone@2.1.0, or the exampleImageLoader which can be seen by uncommenting line 2 of the codepen.

**Comment by Zaid-Safadi** [comment]
Thank you @fcortes for reporting this. I've verified the issue exists in the new cornerstone core when the image.rowPixelSpacing and/or image.columnPixelSpacing is not provided. 

This is causing the scale factor to be calculated as NaN and thus, the math to pan/zoom the image breaks. 

There is an issue that was reported addressing the same thing [here](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/190)

**Comment by Zaid-Safadi** [comment]
@fcortes this is now fixed in 2.2.2
I checked your example by updating the cornerstone reference and it is working as expected.
