### ISSUE TITLE
cornerstone is loading the dicom image, but making its own canvas? 

### ISSUE THREAD

**Issue by jcorry5** [cornerstonejs/cornerstone#263]
I'll start off by saying I'm very new at web development in general never mind cornerstone.

 I got cornerstone libraries added to the scripts and they are running fine as far as I can tell, but on completion  of loading and rendering , the <div> with the canvas contained a new canvas with zero width and height, I'm assuming something cornerstone has done.

Any ideas what would be causing this?

**Comment by fcortes** [comment]
Can you post a working example of this? Maybe you are adding a canvas element yourself to the html source, which is not the way cornerstone works. See [this codepen](https://codepen.io/anon/pen/KRpBBX) for a minimal working setup.

**Comment by swederik** [comment]
Yes Cornerstone will create a canvas inside your enabled element, if there isn't already a canvas inside it with the class 'cornerstone-canvas':

See:

https://github.com/cornerstonejs/cornerstone/blob/master/src/enable.js#L52

https://github.com/cornerstonejs/cornerstone/blob/5069401cafc9d8b91a8db035030b63405c28c505/src/internal/getCanvas.js#L28
