### ISSUE TITLE
Uncaught unknown JPEG marker ffff

### ISSUE THREAD

**Issue by skogsbaer** [cornerstonejs/cornerstone#267]
I have a .dcm file that causes the error "Uncaught unknown JPEG marker ffff" when loading with cornerstonejs. I use the demo at https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html for my tests, but the problem is also present with the OHIF dicom viewer.

I have a file orig.dcm (you find all images attached to this issue) that loads fine. To make the image smaller, I convert it using the command

    dcmcjpeg --encode-extended orig.dcm bad.dcm

The resulting image bad.dcm causes the error "Uncaught unknown JPEG marker ffff". I tried loading the image bad.dcm with Osirix, this work, so I think the bug is in cornerstone and not in dcmcjpeg.

Wenn I use different conversion commands, the resulting images can be loaded with cornerstone:

    dcmcjpeg --quality 85 --encode-extended orig.dcm good1.dcm
    dcmcjpeg --encode-lossless-sv1 orig.dcm good2.dcm

The strange thing is the lowering the JPEG quality to 85 produces an image good1.dcm that works fine with cornerstone.
[bugreport-cornerstone.tar.gz](https://github.com/cornerstonejs/cornerstone/files/1952780/bugreport-cornerstone.tar.gz)

**Comment by chafey** [comment]
Thanks for this bug report - can you move it to the cornerstoneWADOImageLoader repo?  The bug is likely in the jpeg codec here:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/codecs/jpeg.js

Unfortunately this codec is from another project that isn't really maintained - you may need to fix it yourself

**Comment by skogsbaer** [comment]
OK, here is the bugreport for WADOImageLoader: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/195

Closing this issue.
