### ISSUE TITLE
"React Integration Example" on Codesandbox

### ISSUE THREAD

**Issue by leesei** [cornerstonejs/cornerstone#273]
I'm referring to [this link](https://codesandbox.io/s/xj172zjx5w) in the documentation.

The overlay should be placed inside `.viewportElement`.
And `viewport.zoom` should have been `viewport.scale`.

```
  render() {
    return (
      <div>
        <div
          className="viewportElement"
          style={divStyle}
          ref={input => {
            this.element = input;
          }}
        >
          <canvas className="cornerstone-canvas" />
        </div>
        <div style={bottomLeftStyle}>Zoom: {this.state.viewport.scale}</div>
        <div style={bottomRightStyle}>
          WW/WC: {this.state.viewport.voi.windowWidth} /{" "}
          {this.state.viewport.voi.windowCenter}
        </div>
      </div>
    );
  }
```

**Comment by swederik** [comment]
Thanks for the report! I made the changes and it looks like it's updated now:

https://docs.cornerstonejs.org/integration.html

Happy to see at least one person took at look at that example!
