### ISSUE TITLE
CornerstoneNewImage  and CornerstoneImageRendered  not working on older browser

### ISSUE THREAD

**Issue by govi20** [cornerstonejs/cornerstone#279]
I have a angularJS component with following event handler

```
            $("#viewport").on("CornerstoneNewImage", function () {
                ctrl.imageRendered = true;
                $scope.$apply();
            });

```
I have a canvas inside the div element, initially div is hidden and once images starts to load I am making the div visible, I am using **_imageRendered_** variable for that purpose.

I am testing my app on firefox version 40. Issue I am facing here is, after the page CornerstoneNewImage event is triggering only once, after that this event is not triggering.

I have tried CornerstoneImageRendered Event also but this event too triggering only once after the page load.

on firefox 52+ events are working perfectly fine, on every image load these events are triggering but on older browsers only for first image these event are triggered.

PS: I am loading the images using Server Sent Event (EventSource)

**Comment by swederik** [comment]
Hi there,

Which version are you using?

In 2.0.0 we moved to native CustomEvents with lowercased names (https://github.com/cornerstonejs/cornerstone/blob/master/changelog.md#200---2017-12-08).

**Comment by govi20** [comment]
It is 1.x but I'm not sure. Found this in the file /*! cornerstone-core - 0.10.10 - 2017-05-29 | (c) 2016 Chris Hafey | https://github.com/chafey/cornerstone */ 

It is a legacy system. so can't update cornerstone. What are the minimum browser version requirements for these events?

**Comment by swederik** [comment]
This is displayImage at version 0.10.10:

https://github.com/cornerstonejs/cornerstone/blob/0.10.10/src/displayImage.js

If you call it directly from the console, does it throw any errors? Is the event triggered?

Does Firefox 40 support requestAnimationFrame? https://github.com/cornerstonejs/cornerstone/blob/0.10.10/src/internal/requestAnimationFrame.js#L10

If not, it might be worth checking if that polyfill is actually working. 'caniuse' says it should work, though: https://caniuse.com/#feat=requestanimationframe

There's nothing special about the events that were used back then. You should test if you can fire / receive more than one jQuery event. Maybe the event handler is setup incorrectly (it looks fine at first glance, though).

Does the interaction still work? Can you draw tools and/or use window/pan/zoom? If those work then the events definitely fire. If they work but have some issues, then maybe one of the tools is blocking propagation of the event somehow.

**Comment by govi20** [comment]
It is more of back end service issue, SSE Emitter at the backend is not triggering(not sending the data) event
