### ISSUE TITLE
ww/wc no use for some dicom file

### ISSUE THREAD

**Issue by hu3402379** [cornerstonejs/cornerstone#280]
Hi, I found some dicom files can not be change ww/wc, and if you can test this file. when i change the ww/wc, the value is changed, but the image gray value has not changed. I feel very confused, thanks.
[downloadDicomFile.zip](https://github.com/cornerstonejs/cornerstone/files/2037878/downloadDicomFile.zip)

**Comment by deminoth** [comment]
Me too. The problem occurs if there is a `VOILUTSequence` field in dicom files.

**Comment by deminoth** [comment]
@hu3402379  it's not a bug, just a feature. check this example https://github.com/cornerstonejs/cornerstone/blob/master/example/modalityAndVIOLut/index.html
@swederik maybe we can close this issue.
