### ISSUE TITLE
How to integrate into a VUE project

### ISSUE THREAD

**Issue by bianliuzhu** [cornerstonejs/cornerstone#283]
How do I integrate Cornerstonejs into a Vue project, and display Dicom files
Here's the code:

```
import * as cornerstone from "cornerstone-core";
import * as cornerstoneMath from "cornerstone-math";
import * as cornerstoneTools from "cornerstone-tools";
import * as dicomParser from "dicom-parser";
import "../../static/uids.js";
import * as cornerstoneWADOImageLoader from "cornerstone-wado-image-loader";
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
export default {
  name: "HelloWorld",
  data() {
    return {
      loaded: false
    };
  },
  created() {
    cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
    cornerstoneWADOImageLoader.configure({
      beforeSend: function(xhr) {
        // 在这里添加自定义标头(例如 身份验证 符)
        //xhr.setRequestHeader('APIKEY', 'my auth token');
      }
    });
  },
  methods: {
    loadAndViewImage(imageId) {
      let _this = this;
      var element = document.getElementById("dicomImage");
      try {
        var start = new Date().getTime();
        cornerstone.loadAndCacheImage(imageId).then(
          function(image) {
            console.log(image);
            var viewport = cornerstone.getDefaultViewportForImage(
              element,
              image
            );
            cornerstone.displayImage(element, image, viewport);
            if (_this.loaded === false) {
              cornerstoneTools.mouseInput.enable(element);
              cornerstoneTools.mouseWheelInput.enable(element);
              cornerstoneTools.wwwc.activate(element, 1); // ww/wc is the default tool for left mouse button
              cornerstoneTools.pan.activate(element, 2); // pan is the default tool for middle mouse button
              cornerstoneTools.zoom.activate(element, 4); // zoom is the default tool for right mouse button
              cornerstoneTools.zoomWheel.activate(element); // zoom is the default tool for middle mouse wheel
              loaded = true;
            }
          },
          function(err) {
            alert(err);
            console.log(err);
          }
        );
      } catch (err) {
        alert(err);
        console.log(err);
      }
    },
    downloadAndView() {
      let url = document.getElementById("wadoURL").value;
      // prefix the url with wadouri: so cornerstone can find the image loader
      url = "wadouri:" + url;
      // image enable the dicomImage element and activate a few tools
      this.loadAndViewImage(url);
    }
  },
  mounted() {
    cornerstoneWADOImageLoader.external.cornerstone = cornerstone;

    var _this = this;
    var element = document.getElementById("dicomImage");
    cornerstone.enable(element);
    document
      .getElementById("downloadAndView")
      .addEventListener("click", function(e) {
        _this.downloadAndView();
      });

    //Dicom 加载进度监听
    cornerstone.events.addEventListener(
      "cornerstoneimageloadprogress",
      function(event) {
        const eventData = event.detail;
        const loadProgress = document.getElementById("loadProgress");
        loadProgress.textContent = `Image Load Progress: ${
          eventData.percentComplete
        }%`;
      }
    );

    const form = document.getElementById("form");
    form.addEventListener("submit", function() {
      _this.downloadAndView();
      return false;
    });
  }
};
```
But there is an error that I cannot solve, "Uncaught SyntaxError: Unexpected token <", which is very strange. Could you please help me to see what is wrong? thank you

**Comment by dannyrb** [comment]
First and foremost: Please don't email me directly. You can `@mention` me in a GitHub issue, and I'll pop in to respond if I have the time.

Next, you don't need to specify this multiple times:
`cornerstoneWADOImageLoader.external.cornerstone = cornerstone;`

You only need to specify `external` items by your imports, and not in a Vue lifecycle hook. You can see an example of wiring up `external` in the `cornerstone-tools` docs:

https://tools.cornerstonejs.org/installation.html

The next thing that jumps out at me is that I don't see where you're configuring the WADO Image Loader. Normally, you need to provide it a basic configuration that at least points it toward your webworker script. You can find an example config in the `usage` section for the CornerstoneWADOImageLoader:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader#usage

I'm not sure what's up with your syntax error either. Best of luck.

**Comment by bianliuzhu** [comment]
Thanks Danny  Brown Mr guidance, the problem has been solved.
If Danny Mr Brown has time to come to China, please contact me. I will band you taste Chinese food and visit places of interest in China.for this reason Thank you for your help

**Comment by bianliuzhu** [comment]
This is a demo project under the guidance of Mr. Danny Brown.
Implementation of parsing Dicom and displaying in Vue project based on cornerstone
https://github.com/bianliuzhu/CornerstoneVue

**Comment by dannyrb** [comment]
Happy to hear that you got everything working @bianliuzhu! If I'm ever in China, I'll be sure to reach out. Also, thanks for following up with your completed implementation 👍 

Closing this issue. If you have any additional questions, please don't hesitate to create a new issue.
