### ISSUE TITLE
DICOM annonymization

### ISSUE THREAD

**Issue by Viet995** [cornerstonejs/cornerstone#284]
Excuse me!
I want to ask you a question which relate to the anonymization of DICOM image!

Have you worked with anonymization DICOM image?
Can I use cornerstone for anonymization technique? Or any suggestion for me!?

Thank you so much!

**Comment by swederik** [comment]
Not exactly, but you can use [dicomParser](https://github.com/cornerstonejs/dicomParser).

Here's a live example of de-identification in the browser:

https://rawgit.com/cornerstonejs/dicomParser/master/examples/simpleDeIdentify/index.html
