### ISSUE TITLE
The Safari Browser can't display the image

### ISSUE THREAD

**Issue by GleasonBian** [cornerstonejs/cornerstone#286]
The Safari Browser can't display the image,I searched the previous lssues, but I couldn't find the answer.
I made a demo:https://github.com/GleasonBian/CornerstoneNative.
It does not display pictures in Safari browsers
How to solve it? Dicom Image can be displayed in the Safair browser

**Comment by swederik** [comment]
Everything seems to be working fine in Safari for me. Do you have a live link we can check? Are you getting any errors?
