### ISSUE TITLE
BUG in setViewProt.js

### ISSUE THREAD

**Issue by zuopengcy** [cornerstonejs/cornerstone#287]
![image](https://user-images.githubusercontent.com/13266198/42022905-146f25ba-7af1-11e8-8da2-76cb652bdaa6.png)
if the new viewport don't have the attribute 'voi', it will  report a errors
![image](https://user-images.githubusercontent.com/13266198/42022991-5ea92c34-7af1-11e8-9bca-bf77d1ad2ec5.png)
also about arribute ‘scale’

**Comment by chafey** [comment]
voi is a required parameter for viewport - can you debug why it is not set in your application?
