### ISSUE TITLE
 How to get the base64 img you are using in the examples ?

### ISSUE THREAD

**Issue by Im-Goutham** [cornerstonejs/cornerstone#288]
How to get the base64 img you are using in the examples ?

i have only the dicom images , Can they be converted to that format to use. 

If then how to convert and use ?

**Comment by dannyrb** [comment]
More than likely, you don't want to convert your images to base64 for use.

Here's why: https://github.com/cornerstonejs/cornerstone/issues/80#issuecomment-371302373

Further down, you will see additional posts that help illuminate a way to get `cornerstone` to work with an `imageLoader` like:

- The [cornerstoneWADOImageLoader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader) (for rendering DICOMs)
- The [cornerstoneWebImageLoader](https://github.com/cornerstonejs/cornerstoneWebImageLoader) (for rendering JPEGs and PNGs)
