### ISSUE TITLE
How to use dicomParse to parse the correct pixelData information

### ISSUE THREAD

**Issue by Honey-hoo** [cornerstonejs/cornerstone#290]
This way can't get x7fe00010's pixelData,
Thank you .

`var dataSet = dicomParser.parseDicom(byteArray);
      var imageObj = {};
      imageObj.windowCenter = dataSet.string('x00281050');
      imageObj.windowWidth = dataSet.string('x00281051');
      imageObj.accessionNumber = dataSet.string('x00080050');
      imageObj.acquisitionTime = dataSet.string('x00080032');
      imageObj.bitsAllocated = dataSet.string('x00280100');
      imageObj.highBit = dataSet.string('x00280102');
      imageObj.instanceNumber = dataSet.string('x00200013');
      imageObj.institutionName = dataSet.string('x00080080');
      imageObj.patientAge = dataSet.string('x00101010');
      imageObj.patientID = dataSet.string('x00100020');
      imageObj.patientName = dataSet.string('x00100010');
      imageObj.patientSex = dataSet.string('x00100040');
      imageObj.pixelRepresentation = dataSet.string('x00280103');
      imageObj.seriesDescription = dataSet.string('x0008103e');
      imageObj.seriesNumber = dataSet.string('x00200011');
      imageObj.sliceLocation = dataSet.string('x00201041');
      imageObj.sliceThickness = dataSet.string('x00180050');
      imageObj.stationName = dataSet.string('x00081010');
     
     return imageObj;
`

**Comment by chafey** [comment]
I have no idea what you are asking, please provide more detail and post in the dicomParser repository as this doesn't sound cornerstone specific
