### ISSUE TITLE
https://docs.cornerstonejs.org/ is not valid

### ISSUE THREAD

**Issue by ArunRagav** [cornerstonejs/cornerstone#294]
tried opening this page https://docs.cornerstonejs.org/ for reference but not available

**Comment by dannyrb** [comment]
DNS Lookup appears to be fine, and clicking that link loads the docs for me. Are you behind a work proxy, on a VPN, or in any other situation that could affect your ability to view the website? Can you post a screenshot?

**Comment by swederik** [comment]
Seems fine to me too... It's hosted on Github Pages so it should be pretty stable.

**Comment by ArunRagav** [comment]
@dannyrb Here is the screenshot 
<img width="722" alt="capture" src="https://user-images.githubusercontent.com/31159073/43203720-99ebfd20-903c-11e8-9807-d0313502fec7.PNG">

**Comment by dannyrb** [comment]
I'm not sure what to tell you, @ArunRagav. @swederik and I live in very different parts of the world, and have no trouble viewing it. You could... Try a different browser, see if you can view it on your mobile phone over a cell network, or pull down the repository and build the docs (ie. view them locally).

I'm sorry, I wish I could be of more help.
