### ISSUE TITLE
how to read a zip file containing dcm images using cornerstone

### ISSUE THREAD

**Issue by bljd369** [cornerstonejs/cornerstone#311]
Currently I am using https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html for viewing the uploaded dcm files. However this viewer is not working if I upload the zip containing the dcm files, I have this requirement to display the multiple dcm files present in a zip file. I found another viewer https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html#&ui-state=dialog, where the zip containing the dcm files is viewable. Do we have such feature in cornerstone as I have used cornerstone in my application. 

This page https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/stackScroll/index.html allows individual images to be read in group(time series) but does it allow zip file containing dicom images? If yes, can you please add that feature or suggest me how to do that so I will try to contribute myself ?

Thanks

**Comment by chafey** [comment]
Cornerstone does not currently have support from reading DICOM files from a
zip file as you are requesting.  This can definitely be done though via a
custom image loader.  I seem to recall someone else interested in this same
thing in the past - check the forum. To do this yourself, you would
probably want to take a similar approach to how cornerstoneWADOImageLoader
handles multi-frame instrances.  It basically caches the multi-frame in
memory and then allows individual frames to be referenced by imageId.  You
could cache the ZIP in memory and allow individual files in the zip to be
extracted by imageId. Doing this will require an intimate understanding of
how cornerstone image loaders work - please take the time on your side to
understand the source code to your best ability before asking further
questions

**Comment by dannyrb** [comment]
AFAIK, none of our maintained image loaders support zip files. You could fork the cornerstoneWADOImageLoader and add the functionality you need. There is probably an NPM package you can drop into the loadImage method that would accomplish what you want.

I'm not sure that we would be interested in adding this functionality to the maintained loader.

**Comment by swederik** [comment]
What about this one? https://github.com/mbarnig/cornerstoneArchiveImageLoader

@mbarnig

**Comment by mbarnig** [comment]
My RadioLogic project is currently on standby. I hope to resume the project in the coming months and to adapt my code to the current cornerstone versions. 
@bljd369
If you need help tu use my current implementation, your questions are welcome.

**Comment by dannyrb** [comment]
I believe the heart of this question has been answered. If you have additional questions or would like to continue the discussion, I recommend opening a new issue.
