### ISSUE TITLE
Is it possible to change wwwc (brightness/contrast) on a part of the image ?

### ISSUE THREAD

**Issue by marcelfalliere** [cornerstonejs/cornerstone#313]
Hi,

I'm making a cornerstone tools similar to `highlight`, but instead of setting the alpha to `0.7` outside of the selected rectangle, I would like to change the windowWidth/windowCenter (in my limited understanding of cornerstone, this is the brightness/contrast) of the part of the image selected.

So to make this new tool, for which I've forked `cornerstoneTools` repo to give back to the community,  I need to know how to change the b/c of a part of the image.

What would be the correct way to implement such a feature ? There seems to be two strategies :
- create an overlay canvas, and change its viewport (*à la* `magnify` cornerstone tool)
- get the pixel on the canvas for the selected rectangle, and change them

Any help appreciated. Thanks.

**Comment by marcelfalliere** [comment]
We've implemented this feature in a private fork of cornerstone tools.

**Comment by dannyrb** [comment]
@marcelfalliere, a quick heads up. The latest version of tools should make it easier to "p01
