### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstone#322]
Hi!, I wonder if anyone is thinking of a server side rendering version of Cornerstone to allow interacting against a websockets server in charge of rendering the pixeldata?.

**Comment by chafey** [comment]
What would be the benefit of this?  I do think we should add server side support, but I had though it would be used to support implementation of the WADO-RS Retrieve Rendered Transaction API

**Comment by leonardorame** [comment]
One benefit would be practically instant access to CT slices. In the current implementation when a rad wants to go to a slice in the middle of the stack he have to wait until the stack is fully loaded, and with many slices it can take a considerable amount of time.

**Comment by chafey** [comment]
Why does the user have to wait until the stack is fully loaded?  I thought the stack prefetcher supports dynamic priority adjustments?

**Comment by dannyrb** [comment]
@leonardorame, if you would like to move this discussion forward, please feel free to comment and I can open this issue. If you feel your fundamental question/point has changed, please don't hesitate to create a new issue.
