### ISSUE TITLE
How to configure webgl compatible with Android browser

### ISSUE THREAD

**Issue by jkkjinagke** [cornerstonejs/cornerstone#323]
@dannyrb hello dannyrb . Actually, I have a strange question. Why does webgl display images in Android browser?

**Comment by dannyrb** [comment]
I'm not sure I understand your question, @jkkjinagke. Can you add a small reproduction or clarifying information?

**Comment by jkkjinagke** [comment]
@dannyrb In Android, I request that your local IDexample://1 image can be loaded using webgl, but the image I requested with wadouri will not load.

**Comment by jkkjinagke** [comment]
@dannyrb Ngicabanga ukuthi sesivele ilayishiwe futhi ayibonisi. Kuyinto engafanelekile, kodwa akudingeki ngisebenzise i-webgl ukuze ngiyasheshise, kodwa kufanele ngisebenzise i-webgl ukubona ezinye izithombe ze-dcm. Ungakuhlola?

**Comment by jkkjinagke** [comment]
@dannyrb  Inkinga ixazululwe Ngiyabonga, ngashintsha amaconstones e-var canvas = document.createElement ('canvas') kuya var canvas = document.createElement ('canvas') [0]
