### ISSUE TITLE
Error in Synchronizer.js in CornstoneTool

### ISSUE THREAD

**Issue by chetang07** [cornerstonejs/cornerstone#324]
Synchronizer.js:296 Uncaught (in promise) TypeError: Cannot read property 'ELEMENT_DISABLED' of undefined
    at Synchronizer.js:296
    at Array.forEach (<anonymous>)
    at Synchronizer.updateDisableHandlers (Synchronizer.js:295)
    at Synchronizer.addSource (Synchronizer.js:182)
    at Synchronizer.add (Synchronizer.js:208)
    at index.html?_ijt=s3t3fiv8c6khg90lg5hou6vcfk:140

**Comment by dannyrb** [comment]
You may be using incompatible versions of `cornerstone-tools` and `cornerstone-core`. The `ELEMENT_DISABLED` event was added very recently, and only the (still in beta) `vNext` branch should be utilizing it.

**Comment by dannyrb** [comment]
If you're using the latest published versions of `cornerstone-tools` and `cornerstone-core`, you should no longer see this issue. Please create a new issue with a minimal reproduction if you're still experiencing difficulties.
