### ISSUE TITLE
save/export rendered image as JPEG/PNG/?

### ISSUE THREAD

**Issue by fourctv** [cornerstonejs/cornerstone#325]
Is there a way to get the current image being displayed and save/export it as JPEG/PNG?

I mean, the current pixel data on the canvas, which might have been modified with annotations, arrows, angle, windowing, whatever?

Is that available thru a cornerstone call, or should I use DOM tools to grab the actual canvas content?

TIA
julio

**Comment by pieper** [comment]
Yes, just get the canvas data and save it as png (like this example https://github.com/crowds-cure/cancer/blob/v0.1/src/viewer/commands.js#L199-L201)

**Comment by dannyrb** [comment]
FWIW, there is a Save tool in `cornerstone-tools`. There's also a bit of _magic_ to capturing an image with the original resolution, no clipping, and appropriately scaled annotations (line width and font-size may need to be scaled up).

**Comment by sdsy888** [comment]
> FWIW, there is a Save tool in `cornerstone-tools`. There's also a bit of _magic_ to capturing an image with the original resolution, no clipping, and appropriately scaled annotations (line width and font-size may need to be scaled up).

Hi, @dannyrb , thank you for your mentioning, could you be more specific or give an example of fetching the original resolution image from the html canvas?

TIA.

**Comment by dannyrb** [comment]
Hi @sdsy888, there are a number of ways to approach it, but the simplest is:

- Grab the native image resolution from the Image Object
- Set the `EnabledElement`'s viewport, dimensions, scale annotations/text, etc. (for optimal image capture)
- Await image render event, capture image w/ `.toBlob` or `.toDataURL`
- Restore `EnabledElement`'s viewport, dimensions, etc.

FWIW, this bypasses needing to serialize and restore annotation state to a different canvas or server side implementation. If done correctly, it's fast enough, even for large images. There is a _nearly_ imperceptible "blink" when the capturing is happening.

Again, lots of ways, but I believe the above steps require the least amount of effort to produce a much higher quality capture.

**Comment by hassanassaad24** [comment]
@dannyrb how to apply the arrow annotations to the original image, i mean i can grap the original image, i can apply almost all of the viewport and dimensions thingy, but what about the annotations?

**Comment by hassanassaad24** [comment]
@dannyrb Also i tried using the `saveAs` method if i have this image as full resolution, and tried to invert it and applied some rotation and added arrow annotation to it look the difference, the saved image is getting low resolution, also i am getting these  dark borders which are not originally from the image, can you help please

**Original Image:**

![2 25 266771138339415582523661934476990124708](https://github.com/cornerstonejs/cornerstone/assets/150699378/436d3897-73ed-4f95-8910-a12efce7a048)

**Modifyed Image:**

![image_jpeg (3)](https://github.com/cornerstonejs/cornerstone/assets/150699378/0ed845ce-6c5f-4a19-acd3-ab69874ac14a)
