### ISSUE TITLE
Under webgl, Android loading does not show up

### ISSUE THREAD

**Issue by ShunKeJiang** [cornerstonejs/cornerstone#327]
@dannyrb After I set the rendering mode to webgl, I can render it normally in PC and Apple, but the rendering in Android is black. Can you help me answer this is whether Android does not support too much rgb rendering. Thank you. Cheers

**Comment by jkkjinagke** [comment]
@dannyrb Yes, but it's strange that your display is normal, I can't all feel very strange. I am requesting with WADO-URI

**Comment by dannyrb** [comment]
Related: https://github.com/cornerstonejs/cornerstone/issues/132
Related (iOS): https://github.com/cornerstonejs/cornerstone/issues/367

If you're able to provide a minimal reproduction and device/browser specifics, I can re-open and continue to troubleshoot this issue. I have real and emulated devices available for most of the popular combinations.

It's worth noting that WebGL issues like this can be device specific and tied to the GPU, and not necessarily OS specific.
