### ISSUE TITLE
Is there any way to get the rendering status ?

### ISSUE THREAD

**Issue by sdsy888** [cornerstonejs/cornerstone#328]
Is there any way to get the rendering status such as "rendering completed"?

I want to fetch the canvas content (which is rendered by this API), but currently I can only set the browser to wait for a specific time set by `time` function. 

So I'm wondering if there's any method to let the fetching program know when the rendering is done?

TIA

**Comment by dannyrb** [comment]
@sdsy888 this event is emitted when an image is rendered:

- https://github.com/cornerstonejs/cornerstone/blob/master/src/events.js#L14

There are other helpful events listed in that file. Searching the enumeration should provide examples of listening for events, and use cases that they're often paired with.

**Comment by sdsy888** [comment]
@dannyrb  Thank you for your kind reply! It's really helpful.
 I've found the event you mentioned, but encountered another problem:
 I found the `javascript` triggers the `event` like this: `$(a.element).trigger("CornerstoneImageRendered",b)`. But I cannot find this specific event in the  **events Listener** of DevTools of Chrome.

Then, how can I listen or capture this event `"CornerstoneImageRendered"` through `event listener` or javascript?

Thank you!

**Comment by dannyrb** [comment]
@sdys888, I think we handle events two different ways. Either:

`cornerstone.events.addEventListener('eventname', callbackFn)`
See: https://github.com/cornerstonejs/cornerstone/blob/master/src/events.js#L54-L67

OR

```
const element = document.querySelector('#my-element');
element.addEventListener('eventname', callbackFn)`
```
See: https://github.com/cornerstonejs/cornerstone/blob/master/src/triggerEvent.js

The first allows you to subscribe to events at the "library" level. The second allows you to listen for events for a specific enabledElement.

It looks like `ImageRendered` is only "emitted" for the `enabledElement` it is associated with:
https://github.com/cornerstonejs/cornerstone/blob/12da9ed267499345ef192d9e5f214cc79122ffc3/src/internal/drawImageSync.js#L78

We actually have an example for this specific event located here: https://github.com/cornerstonejs/cornerstone/blob/12da9ed267499345ef192d9e5f214cc79122ffc3/example/eventhandling/index.html#L76-L112

**Comment by sdsy888** [comment]
@dannyrb Thank you for the reply!
I will try this method!

**Comment by dannyrb** [comment]
@sdsy888, let me know if you are still encountering issues. I'm going to close this issue for now as it appears to have been resolved.
