### ISSUE TITLE
Live demo examples 404 Not found

### ISSUE THREAD

**Issue by HRK44** [cornerstonejs/cornerstone#335]
On all the examples found here : 

I have this error 404 Not found https://rawgit.com/cornerstonejs/cornerstone/master/dist/cornerstone.js

https://rawgit.com/cornerstonejs/cornerstone/master/example/index.html

**Comment by dannyrb** [comment]
Latest version would be here: https://unpkg.com/cornerstone-core@2.2.8/dist/cornerstone.js

**Comment by dannyrb** [comment]
These are now pulling from `unpkg` 👍
