### ISSUE TITLE
Any plans to maintain typings?

### ISSUE THREAD

**Issue by talkdirty** [cornerstonejs/cornerstone#336]
Hey there!

Are there any plans to maintain typescript typings for this project? I think the development experience could benefit tremendously from this!

Cheers!
Georg

**Comment by dannyrb** [comment]
@talkdirty, there haven't been any formal talks, but I've started to look into the level of effort involved and the benefits of doing so. I think that we eventually will. The biggest hurdle would be resources and a champion.

If this is something you're passionate about, we could talk specifics in the Cornerstone Slack group?

**Comment by talkdirty** [comment]
Hey Danny, thanks for the response! Our team actually started maintaining a
repository with typings for cornerstone-core, cornerstone-math,
cornerstone-tools, cornerstone-wado-image-loader, and dicom-parser. They
are so far very incomplete though. I can't promise anything, as this isn't
our highest priority, but if we decide to spend more time to spend more
time into generating complete typings from source code (dtsmake looks very
promising for this), we will of course contribute these back to cornerstone.

Am Mi., 12. Dez. 2018 um 14:20 Uhr schrieb Danny Brown <
notifications@github.com>:

**Comment by jussimattila** [comment]
I've also built extremely incomplete typings for an old version of cornerstone (around v0.10.8 time frame). I'd be interested in contributing, but unfortunately cannot commit to championing this effort.

**Comment by dannyrb** [comment]
I think I've answered the heart of this question and will close the issue for now.

I am very open to typing contributions, but would appreciate guidance on the migration efforts/plan.
