### ISSUE TITLE
Error combining 2 libraries: Can not read property 'SUPPORT_POINTER_EVENTS' of undefined

### ISSUE THREAD

**Issue by DavidHS03** [cornerstonejs/cornerstone#342]
Hello community, I hope you can help me solve this issue:
Combine 2 libraries (cornerstoneWADOImageLoader-> wadouri / index.html) and (cornerstoneTools-> alltouchtools / index.html)

cornerstoneWADOImageLoader: I use this library to convert a URL to an object image, then I'm interested in the cornerstoneTools library to get the tools that are used in that example.
If the DICOM image is shown in my element document.getElementById ('dicomImage');
But the tools do not work and they send me an error in the console:

Uncaught (in promise) TypeError: Can not read property 'SUPPORT_POINTER_EVENTS' of undefined
    at Object.r [as enable] (cornerstoneTools.min.js: 2)
    at visualizar_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 779
r @ cornerstoneTools.min.js: 2
(anonymous) @view_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 779
Promise.then (async)
getImagetools @view_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 772
loadAndViewImage @ visualizar_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 699
getImage @ visualizar_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 689
(anonymous) @view_imagen_new.php? id = WEEvaENpL3VyK3BxTER3cTFYYVJqUT09: 661
dispatch @ vendors.min.js: 3
q.handle @ vendors.min.js: 3

I would really appreciate it if you can help me.

**Comment by dannyrb** [comment]
Closing. Duplicates: https://github.com/cornerstonejs/cornerstoneTools/issues/768
