### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by tunglt1810** [cornerstonejs/cornerstone#345]
I have test on your example site many times on Chrome and Firefox. It shows me renderer using webgl slowly, sometime it's about 200%. Can you explain these issue

**Comment by dannyrb** [comment]
It's been a couple of months. I'm going to close this issue. My best bet is that browser's implement things differently 🤷‍♂️ 

I know we've seen various vendors preform worse/better than others from version to version. I'm not sure it's possible for us to have much insight into _why_
