### ISSUE TITLE
Loading Dicom image from pynetdicom

### ISSUE THREAD

**Issue by Neuroforge** [cornerstonejs/cornerstone#346]
(QUESTION)
Hello,

I am looking at creating a server backend which uses pynetdicom to get a dicom image from a PACS server.

The work flow would be javascript ajax -> Python server -> ajax.

It has been suggested that the pydicom dataset could be serialised into a json object in the following way.

https://github.com/pydicom/pydicom/issues/319

"I've used the following to convert a dataset to a dict (for storing as JSON) if it's any help"

pydicom dataset -> Python dictionary -> JSON object

Would it be possible to load this into cornerstonejs? What would be the appropriate method to do this?

Regards,

Daniel

**Comment by dannyrb** [comment]
@Neuroforge, most data is loaded into `cornerstone` using an "image loader". Existing examples are:

- [Web Image Loader](https://github.com/cornerstonejs/cornerstoneWebImageLoader)
    - PNG and JPEG images (does not load metadata)
- [WADO Image Loader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader)
    - DICOM images; parses metadata and associates with image ids
- [Nifti Image Loader](https://github.com/flywheel-io/cornerstone-nifti-image-loader)
    - Nifti images

The workflow is roughly:

- load `cornerstone.js`
- load a cornerstone image loader
- "register" the cornerstone image loader
    - `cornerstone.registerImageLoader('someScheme', imageLoader.loadImageFn);`
    - Example Schemes: `http`, `https`, `file`, `wadouri`, `wadors`
- Load an image
   - `cornerstone.loadImage('imageLoaderScheme:unique-image-id')`
   - Example ImageIds: `https://example.com/my-dicom?id=123`, `file://C:\dicom.dcm`

A bit rough, but I hope that helps. Feel free to ask additional questions and for clarification.
