### ISSUE TITLE
Presentation State

### ISSUE THREAD

**Issue by kofifus** [cornerstonejs/cornerstone#348]
How do I read/apply a presentation state file (.pre) ? is there any docs/example for this ?

Thanks!

**Comment by dannyrb** [comment]
@kofifus, I don't know that I've ever come across a .pre file. Do you know in what situations one would expect to deal with them? If you have an example file, I'd be curious to take a peak at it.

**Comment by kofifus** [comment]
As far as I can tell from 
https://github.com/cornerstonejs/cornerstone/issues/249
and
https://github.com/cornerstonejs/cornerstoneTools/issues/780#issuecomment-459419871

Cornerstone has the ability to apply a presentation state but I do not know how and can find no docs about it.

Thanks!

**Comment by jdnarvaez** [comment]
A DICOM presentation state is just a DICOM file without pixel data. You can use the dicom parser library to parse it, then these values have sequences that indicate which images/frames are referenced and how these values should override the original values of the other DICOM file.

**Comment by kofifus** [comment]
I'll close this for now, hopefully someone can implement Cornerstone support in the future.
