### ISSUE TITLE
WW/WC not working for some DICOM files

### ISSUE THREAD

**Issue by androidsystest001** [cornerstonejs/cornerstone#356]
**(QUESTION)**
I working on a medical project (i don't have medical knowledge (ex: DICOM file))
I have two DICOM files. Can download from url:
[test_DICOM_WW_WC_ng_file.dcm](https://github.com/androidsystest001/Medic/raw/master/web/medic/assets/test_DICOM_WW_WC_ng_file.dcm)
[test_DICOM_WW_WC_ok_file.dcm](https://github.com/androidsystest001/Medic/raw/master/web/medic/assets/test_DICOM_WW_WC_ok_file.dcm)

**Steps to Reproduce**
Go to URL: https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

- If load the file: test_DICOM_WW_WC_ok_file.dcm
I can change WW/WC by left mouse button.

- If load the file: test_DICOM_WW_WC_ng_file.dcm
I **can't change** WW/WC by left mouse button.
(My customer reported a bug in this case)

I try find some information, and go to URL: https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html

- If load the file: test_DICOM_WW_WC_ok_file.dcm
_WindowCenterWidthExplanation_ property missing.

- If load the file: test_DICOM_WW_WC_ng_file.dcm
I can see property: _WindowCenterWidthExplanation_ : "**linear LUT**"

Could you please give me some infomation / solution in this case?

Thanks./

**Comment by fomin-max** [comment]
I have some problem when i using cornerstoneTools package.

I found out that the WW/WC tool doesn't work only with DICOM files that have the `VOILUTSequence` field.

So my decision - remove this field and it working for me. If you don't know how make it, you can use my script - [DICOM Anonymizer](https://github.com/fomin-max/dicom_anonymizer).

I hope this decision helped you :)

**Comment by swederik** [comment]
You can also just unset the Viewport's VOI LUT field. Here's an example of toggling it on / off:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/31a9b5a5eb267cfdfcf6db45218ad70c6d7ee115/examples/wadouri/index.html#L332-L336
