### ISSUE TITLE
Image scaling in javascript and HTML5 algorithm with cornersstone pixeldata results in coarse images?

### ISSUE THREAD

**Issue by jmanden** [cornerstonejs/cornerstone#364]
Dear Cornerstone community,

I'm hoping someone could be so kind to weight in on the following conundrum related to Cornerstone raised on stackoverflow:
https://stackoverflow.com/questions/54934214/image-scaling-in-javascript-and-html5-algorithm-for-pixeldata-results-in-coarse

Your sincerely

**Comment by dannyrb** [comment]
I'm guessing the goal here is to produce a cleaner image when resizing in the viewport? While I understand your frustration, your question isn't really specific to any `Cornerstone.js` repo. You may want to try your luck on our [Google Group](https://groups.google.com/forum/#!forum/cornerstone-platform)

I'm going to close this issue for now.
