### ISSUE TITLE
Cornerstonejs cannot open dicom files from pdf2dcm

### ISSUE THREAD

**Issue by Neuroforge** [cornerstonejs/cornerstone#368]
Hello,

I have used the pdf2dcm tool to encapsulate a pdf file to dicom. However, this dataset cannot be accessed with cornerstone? I need to either load the pdf dicom dataset or identify it as a pdf dicom before try to use the image loader.

https://support.dcmtk.org/docs/pdf2dcm.html

How can i user conerstonejs to identify which files are images and which are pdf?

I am unable to load pdf2dcm generated dicom file into cornerstone

1) Orthanc and Radiant both display the dicom file as a pdf.

2) Dataset tags included in the PDF, important fields removed with "XXXXX"

> 0008,0005 (SpecificCharacterSet): ISO_IR 100
> 0008,0012 (InstanceCreationDate): 20190315
> 0008,0013 (InstanceCreationTime): 033259
> 0008,0016 (SOPClassUID): 1.2.840.10008.5.1.4.1.1.104.1
> 0008,0018 (SOPInstanceUID): 1.2.276.0.7230010.3.1.4.0.46329.1552620779.840126
> 0008,0020 (StudyDate): Saturday, June 20, 2015
> 0008,0023 (ContentDate):
> 0008,002a (AcquisitionDateTime):
> 0008,0030 (StudyTime):
> 0008,0033 (ContentTime):
> 0008,0050 (AccessionNumber): 2636912
> 0008,0060 (Modality): DOC
> 0008,0064 (ConversionType): WSD
> 0008,0070 (Manufacturer):
> 0008,0090 (ReferringPhysicianName):
> 0010,0010 (PatientName): XXXXXXXXXXXXXX
> 0010,0020 (PatientID): XXXXXXXXXXXXXX
> 0010,0030 (PatientBirthDate): XXXXXXXXXXXXXX
> 0010,0040 (PatientSex): F
> 0020,000d (StudyInstanceUID): XXXXXXXXXXXXXX
> 0020,000e (SeriesInstanceUID): XXXXXXXXXXXXXX
> 0020,0010 (StudyID): XXXXXXXXXXXXXX
> 0020,0011 (SeriesNumber): 1
> 0020,0013 (InstanceNumber): 1
> 0028,0301 (BurnedInAnnotation): YES
> 0040,a043 (ConceptNameCodeSequence): []
> 0042,0010 (DocumentTitle):
> 0042,0011 (EncapsulatedDocument): XXXXXXXXXXXXXX
> 0042,0012 (MIMETypeOfEncapsulatedDocument): application/pdf

Full error message is as below.

> 
> message: "Uncaught (in promise): Error: The file does not contain image data.↵Error: The file does not contain image data.↵    at t.default (https://unpkg.com/cornerstone-wado-image-loader@2.1.4/dist/cornerstoneWADOImageLoader.min.js:2:13977)↵    at https://unpkg.com/cornerstone-wado-image-loader@2.1.4/dist/cornerstoneWADOImageLoader.min.js:2:17456↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8101/polyfills.js:2733:26)↵    at Object.onInvoke (http://localhost:8101/vendor.js:62335:33)↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8101/polyfills.js:2732:32)↵    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:8101/polyfills.js:2483:43)↵    at http://localhost:8101/polyfills.js:3217:34↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8101/polyfills.js:2766:31)↵    at Object.onInvokeTask (http://localhost:8101/vendor.js:62326:33)↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8101/polyfills.js:2765:36)"
> stack: "Error: Uncaught (in promise): Error: The file does not contain image data.↵Error: The file does not contain image data.↵    at t.default (https://unpkg.com/cornerstone-wado-image-loader@2.1.4/dist/cornerstoneWADOImageLoader.min.js:2:13977)↵    at https://unpkg.com/cornerstone-wado-image-loader@2.1.4/dist/cornerstoneWADOImageLoader.min.js:2:17456↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8101/polyfills.js:2733:26)↵    at Object.onInvoke (http://localhost:8101/vendor.js:62335:33)↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8101/polyfills.js:2732:32)↵    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:8101/polyfills.js:2483:43)↵    at http://localhost:8101/polyfills.js:3217:34↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8101/polyfills.js:2766:31)↵    at Object.onInvokeTask (http://localhost:8101/vendor.js:62326:33)↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8101/polyfills.js:2765:36)↵    at resolvePromise (http://localhost:8101/polyfills.js:3159:31)↵    at Function.ZoneAwarePromise.reject (http://localhost:8101/polyfills.js:3249:20)↵    at t.default (https://unpkg.com/cornerstone-wado-image-loader@2.1.4/dist/cornerstoneWADOImageLoader.min.js:2:13970)↵    at https://unpkg.com/cornerstone-wado-image-loader@2.1.4/dist/cornerstoneWADOImageLoader.min.js:2:17456↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8101/polyfills.js:2733:26)↵    at Object.onInvoke (http://localhost:8101/vendor.js:62335:33)↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:8101/polyfills.js:2732:32)↵    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:8101/polyfills.js:2483:43)↵    at http://localhost:8101/polyfills.js:3217:34↵    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8101/polyfills.js:2766:31)"
> __proto__: Object

**Comment by dannyrb** [comment]
Hmm... I'm pretty sure we have a whitelist of SOPClassUIDs. Anything not in that list, we assume is an "attachment"

**Comment by swederik** [comment]
Cornerstone displays pixel data. Encapsulated PDFs do not contain pixel data, they contain PDF data. You can render them with your browser PDF reader, you don't need Cornerstone for this.

There's an example here: https://rawgit.com/cornerstonejs/dicomParser/master/examples/encapsulatedPDF/index.html

and here's a sample file: https://www.dropbox.com/s/rz2065w90lak9qx/sample.dcm?dl=0

**Comment by dannyrb** [comment]
> How can i user conerstonejs to identify which files are images and which are pdf?

If you're creating the DICOM file, and it sounds like you are, you can set metadata fields in a way that flags the file as a PDF file. I'm not sure how "correct" it is, but you can use the unique [SOP Class UID](https://dicom.innolitics.com/ciods/cr-image/sop-common/00080016) to indicate the file is an "attachment" or non-DICOM, and the [image comments field](https://dicom.innolitics.com/ciods/cr-image/general-image/00204000) to provide more context/information about what you've wrapped.

I think @swederik and I have answered the heart of your question. If you believe we have not, please feel free to continue the conversation or create a new issue 👍

**Comment by malaterre** [comment]
IMHO @swederik has given the right answer here. I suspect this issue can be closed.
