### ISSUE TITLE
multi windows synchronizer don't work in angular4

### ISSUE THREAD

**Issue by bocao9107** [cornerstonejs/cornerstone#378]
`var synchronizer = new cornerstoneTools.Synchronizer("CornerstoneImageLoaded ", 
                                cornerstoneTools.stackScrollSynchronizer);`
`cornerstone.enable(this.elements[0]);
 cornerstone.enable(this.elements[1]);`
`cornerstoneTools.stackScrollWheel.activate(this.elements[0]);
  cornerstoneTools.stackScrollWheel.activate(this.elements[1]);`
cornerstoneTools.addStackStateManager(this.elements[this.currentIndex], ['stack', 'playClip']); // ,['playClip']
                cornerstoneTools.addToolState(this.elements[this.currentIndex], 'stack', this.dicomSeries[this.currentIndex].stack);
                cornerstoneTools.addStackStateManager(this.elements[1], ['stack', 'playClip']); // ,['playClip']
                cornerstoneTools.addToolState(this.elements[1], 'stack', this.dicomSeries[0].stack);``
`cornerstoneTools.stackScrollSynchronizer(synchronizer , this.elements[0], this.elements[1]);`

when I scroll the first elements other doesn't scroll

**Comment by dannyrb** [comment]
If this is still an issue for you, please consider creating a new issue with a minimal reproduction in the `cornerstone-tools` repository.
