### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by vela1606** [cornerstonejs/cornerstone#379]
Have you guys seen this?
I don't see any issues with the image and renders fine on Horos/Osirix

![Screen Shot 2019-04-26 at 2 34 37 PM](https://user-images.githubusercontent.com/312212/56831269-9a6f0300-6836-11e9-915a-ac2f0c82bb9c.png)

**Comment by dannyrb** [comment]
@vela1606 Can you provide enough information for us reproduce this issue locally? Or, stand-up a rendering demo using codepen or codesandbox?

**Comment by vela1606** [comment]
webgl did the trick

const options = {
    renderer: 'webgl'
};

**Comment by dannyrb** [comment]
Hmm... In a perfect world, that option should produce a consistent result for the same image data.
