### ISSUE TITLE
Reset the canvas before loading new image

### ISSUE THREAD

**Issue by dongtanhuy** [cornerstonejs/cornerstone#381]
I create AI Prediction button to draw some polygons on the image. But when I scroll to move to the next image, the old polygons still appeared on the canvas. How can I reset the canvas to remove the old polygons before rendering the new image? Thanks.
![Screen Shot 2019-05-07 at 09 53 40 (2)](https://user-images.githubusercontent.com/12930043/57268781-563df700-70af-11e9-9f65-769e3f3a4bff.png)

**Comment by dannyrb** [comment]
Did you create a custom `cornerstone tool` to render the polygons, or are you rendering them outside of the tool system? If you're rendering the images outside of the tool system, you may have other issues not yet accounted for.

What you came here for: https://docs.cornerstonejs.org/api.html#updateimage

Calling updateImage on the enabledElement should trigger a redraw.

**Comment by dongtanhuy** [comment]
@dannyrb, No, I don't create a custom `cornerstone tool`, I just find the canvas by `document.getElementsByClassName("cornerstone-canvas")[0]`, then I use context2D to draw polygons on this canvas.
I've try to use `updateImage` API like this
```js
const canvas = document.getElementsByClassName('cornerstone-canvas')[0];
cornerstone.enable(canvas);
cornerstone.updateImage(canvas, true);
```
but I got an error ` updateImage: image has not been loaded yet`

**Comment by d13g0** [comment]
This could happen because the image hasn't finished loading yet. I had a similar issue and what I did was simply a try catch:

`
const element = ...
try{
cornerstone.reset(element);
cornerstone.updateImage(element);
} catch (error){
//try later?
}
`

**Comment by dannyrb** [comment]
@dongtanhuy if you're still experiencing issues, I recommend using a custom Cornerstone Tool. If you need assistance creating one, or adding one to the latest OHIF Viewer, please feel free to create a new issue in the appropriate repository.
