### ISSUE TITLE
Overlay Data unable to display!

### ISSUE THREAD

**Issue by tanxu1120** [cornerstonejs/cornerstone#386]
[SC.1.3.12.2.1107.5.1.4.73406.zip](https://github.com/cornerstonejs/cornerstone/files/3225452/SC.1.3.12.2.1107.5.1.4.73406.zip)

**Comment by dannyrb** [comment]
Can you provide more information, or a demo on codepen w/ your test data? I'm a bit wary of downloading ZIP files.

**Comment by tanxu1120** [comment]
This is a DICOM with Overlay Data (60xx, 3000), cornerstone can't display.
I can display it with other DICOM Viewer.
![155902369722](https://user-images.githubusercontent.com/37609756/58454908-7d3d9500-8152-11e9-90c7-0b002bdae16c.jpg)
![15590234178763](https://user-images.githubusercontent.com/37609756/58454913-862e6680-8152-11e9-85d4-185087d88ff6.jpg)

**Comment by dannyrb** [comment]
This was done in `tools`, but is awaiting a final review/merge. You can utilize it yourself if you're unable to wait: https://github.com/cornerstonejs/cornerstoneTools/pull/860
