### ISSUE TITLE
is it possible to capture the active viewport as key image. by using measurement tool or any action button?

### ISSUE THREAD

**Issue by Malik-Adil** [cornerstonejs/cornerstone#387]
I am working on some medical product and I need to capture the current state of the image which is loading in the canvas. Is any function available for capturing the image into some form e.g base64, jpeg, png, etc

**Comment by dannyrb** [comment]
MDN Docs: [HtmlCanvasElement.toDataURL()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)

Keep in mind, this will create an exact copy of what's currently displayed in the viewport. More robust methods might include:

    - Serializing the annotation/viewport data, and sending it to the server to create a new image
    - Adjusting the canvas, before capture, to show ideal image

Past related comments:

- https://github.com/cornerstonejs/cornerstone/issues/325#issuecomment-435966847
- https://github.com/cornerstonejs/cornerstoneTools/issues/260
