### ISSUE TITLE
possible semantic inconsistency using enabled elements

### ISSUE THREAD

**Issue by d13g0** [cornerstonejs/cornerstone#389]
Possible inconsistency here?

```
const enabledElement = cornerstone.getEnabledElement(domElement);
cornerstone.reset(enabledElement); //this fails
cornerstone.reset(enabledElement.element); // this works
```

**Comment by swederik** [comment]
Hi @d13g0,

I'd say this is intentional. Most of the external API calls take the HTML Element as the input e.g. `getViewport`, `setViewport`, `displayImage`, and so on.
