### ISSUE TITLE
WWWC issue when changing quality of image

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstone#397]
Hi, to improve the UX of my viewer, when dealing with big images I'm loading first a very low quality version of the image, calling `cornerstone.getDefaultViewportForImage` followed by `cornerstone.displayImage`. Then, the full quality version is loaded, but this time only calling `cornerstone.displayImage`, because I want to keep the current viewport (the user could have panned, zoomed or ww/wc the image at this point).

On many images the ww/wc of the image is correct after applying the full quality image, but on some CR images I'm getting a too white or too dark result, let me explain with an example:

This is the low quality image:

![image](https://user-images.githubusercontent.com/1405017/62013105-c3b86b80-b164-11e9-8c86-00670cc08c26.png)

And this is the high quality image that replaces the former:

![image](https://user-images.githubusercontent.com/1405017/62013137-fe220880-b164-11e9-93b4-3a7ecfed8f27.png)

I think this is related to the fact that VOI/LUT is calculated on the available pixel data. As the original image has a very limited range, when applying the same function to the full quality image, the result is the very black image. Is there a way to re-calculate the VOI/LUT without calling `cornerstone.getDefaultViewport`, as I don't want to change zoom or pan.

**Comment by dannyrb** [comment]
- `displayImage` takes an [optional 3rd parameter, `viewport`](https://github.com/cornerstonejs/cornerstone/blob/master/src/displayImage.js#L20).
- The default width/center values for your image should be on the [image object created by your image loader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L125-L126). 
- The `cornerstoneWADOImageLoader` will [calculate those values if they are not specified by the expected DICOM tags](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L182-L188).

0. Load your low quality image
1. Load your high quality image
2. Get the viewport of the currently displayed low quality image
3. Copy the viewport, and update it's width/center using the width/center of the high quality image
4. Call `displayImage` with the new image and modified viewport.

**Comment by leonardorame** [comment]
Thanks @dannyrb, I ended up doing exactly that.
