### ISSUE TITLE
 base64 images not working with example image loader

### ISSUE THREAD

**Issue by vanye007** [cornerstonejs/cornerstone#404]
We tried replacing the base64 image variable in the example image loader with ours, it displayed a fragmented image. We noticed that the example image loader binary data mime type was "application/octet-stream"

**Comment by dannyrb** [comment]
The example image loader isn't really good for anything other than providing a minimal example with no external dependencies. We use it so you don't need to configure an external data source to test out rendering and core library functionality. It also shows, at it's simplest form, the contract an image loader needs to follow.

If you're trying to load your own data, you might want to take a look at the `cornerstoneWadoImageLoader` repository:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader
