### ISSUE TITLE
how to load dcm images from URI address

### ISSUE THREAD

**Issue by miaozhi** [cornerstonejs/cornerstone#407]
how to load dcm images from URI address?
for exg.
http://192.168.1.100/xxxx/xxx.dcm

thank you very much!

**Comment by anshulcww** [comment]
Please help !! 
If you have solved this issue

**Comment by dannyrb** [comment]
Cornerstone has methods like `loadImage` and `loadAndCacheImage`
These use any registered image loader with a matching scheme to load image data.
The most popular one is: https://github.com/cornerstonejs/cornerstoneWADOImageLoader

If you register and configure the cornerstoneWADOImageLoader, it can be used to load images with a URI address like the one you've specified. Notably:

- https://github.com/cornerstonejs/cornerstoneWADOImageLoader#key-features
- https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/wadouri/index.html
