### ISSUE TITLE
How can we pass props to a tool to draw lines according to the prerequisite data present with us?

### ISSUE THREAD

**Issue by rish-hub** [cornerstonejs/cornerstone#413]
How can we pass props to a tool in order to draw lines on an image according to the prerequisite data present with us?
I am bit confuse on even creating a new tool or this can be done through an existing tool, my main aim to draw lines automatically on the basis of data provided to the tool TIA.

**Comment by dannyrb** [comment]
Have you looked at `cornerstone-tools`?

- https://github.com/cornerstonejs/cornerstoneTools

It provides a way to create tools, or leverage many common tools that come bundled with the library. Tool's have "ToolState" that can be serialized, persisted, and restored.

**Comment by rish-hub** [comment]
Thanks @dannyrb..  I could find the way in cornerstone-tools documentation, to update/add state of respective tool state and rest is taken care for the tool itself
