### ISSUE TITLE
Issues with HRCT images

### ISSUE THREAD

**Issue by MicheleZak** [cornerstonejs/cornerstone#417]
Hello guys,

I got some high resolution computed tomography (HRCT) studies which are not displayed as expected. The dicom files are from a "LightSpeed VCT" asset.

Here's the link to the study on dicomlibrary, on which, I think, the images are displayed correctly:
https://www.dicomlibrary.com?study=1.2.826.0.1.3680043.8.1055.1.20191104185916632.189252767.7426759

The link to download the study:
https://www.dicomlibrary.com?requestType=WADO&studyUID=1.2.826.0.1.3680043.8.1055.1.20191104185916632.189252767.7426759&manage=502e9d54f0077815db6a2b9e4a534e08

And here's a screenshot of the images on my viewer.
![Screenshot_2019-11-05 Exam Viewer](https://user-images.githubusercontent.com/6943529/68198524-83b32100-ffbc-11e9-9811-3f3fc5fe362b.png)

Do you have any idea of what the issue could be?
Thanks

**Comment by chafey** [comment]
The images look like they are displaying properly to me, what is the problem you are seeing?

**Comment by MicheleZak** [comment]
To my untrained eye, there is a noticeable difference between how the image gets rendered in my viewer versus how it gets rendered in 3 other viewers I tried (MedDream, Radiant, K-Packs) - see screenshot; this was also reported by one of my users.


MedDream:

![dicom-meddream-contrast-diff](https://user-images.githubusercontent.com/6943529/68297053-5470e280-0096-11ea-9a7a-bff401533007.png)

K-Packs:

![dicom-contrast-diff](https://user-images.githubusercontent.com/6943529/68297071-5cc91d80-0096-11ea-967c-ab7d9da78d9e.png)

Radiant:

![dicom-radiant-contrast-diff](https://user-images.githubusercontent.com/6943529/68297085-63579500-0096-11ea-908a-83d74a5f3187.png)

**Comment by dannyrb** [comment]
IANAR, but how do they compare at the same window width/center? Or is part of the issue different initial window level values?

**Comment by MicheleZak** [comment]
I apologize. 
I wasn't aware of those values and their meaning. Plus, I had tunnel vision and didn't note they were different, what a fail. I am sorry to have wasted your time.
Thank you a lot.

**Comment by dannyrb** [comment]
@MicheleZak, no worries. Please don't hesitate to reach out with questions in the future ^_^
