### ISSUE TITLE
this image is abnormal

### ISSUE THREAD

**Issue by wmxj** [cornerstonejs/cornerstone#421]
[1.2.156.14702.18.1.3.420190911135308485.20190917103412.zip](https://github.com/cornerstonejs/cornerstone/files/3915243/1.2.156.14702.18.1.3.420190911135308485.20190917103412.zip)
![1](https://user-images.githubusercontent.com/1752767/70030412-270b4c00-15e4-11ea-9675-e4bf34125228.png)

**Comment by dannyrb** [comment]
What is the expected output? Comparison in a known good viewer? Any tags related to VOI LUT?

**Comment by wmxj** [comment]
> What is the expected output? Comparison in a known good viewer? Any tags related to VOI LUT?

![2](https://user-images.githubusercontent.com/1752767/70074971-c6f1c580-1636-11ea-840e-ff8a7d480fee.png)

I view this DCM in Sante tool for normal, see this figure. If you use cornerstone to view this DCM, the above exception will be displayed,

**Comment by wmxj** [comment]
![2](https://user-images.githubusercontent.com/1752767/70075110-0ddfbb00-1637-11ea-9575-d4baf5c7eab8.png)

**Comment by dannyrb** [comment]
https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

### With VOI LUT Applied

![image](https://user-images.githubusercontent.com/5797588/70076023-f28b9600-15cb-11ea-8995-b1f893a02c6c.png)

### With VOI LUT toggled off

![image](https://user-images.githubusercontent.com/5797588/70076044-fcad9480-15cb-11ea-9da5-8e039142560a.png)

**Comment by wmxj** [comment]
Thank you very much
