### ISSUE TITLE
Problem with displaying DICOM

### ISSUE THREAD

**Issue by drozdzynski** [cornerstonejs/cornerstone#429]
Hello,

I have a problem with specific dicom, when I open it in the cornerstone the image is just black.

`viewport.voi` for this image is:
```
windowWidth: 16383
windowCenter: 8191.5
```

After I did some changes with `viewport.voi`:
```
windowWidth: 1123
windowCenter: 561.5
```
It looks like this:
![voi-changes](https://user-images.githubusercontent.com/15519639/71717686-1c2d1c80-2e19-11ea-9922-f7d08277bc0c.png)

And this is how it should look like:
![should](https://user-images.githubusercontent.com/15519639/71717697-29e2a200-2e19-11ea-93b9-63f76874ce95.jpg)

Dicom file basic information:
```
Explicit VR Little Endian

SpecificCharacterSet : "ISO_IR 100"
ImageType : "ORIGINAL\PRIMARY\GDC"
SOPClassUID : "1.2.840.10008.5.1.4.1.1.4" [ MR Image Storage ]
```

Any idea how to solve this issue? If you need more info about this file please let me know.

**Comment by swederik** [comment]
What type of compression? What is the rescale slope and intercept? Can you de-identify the image for debugging?

**Comment by drozdzynski** [comment]
Here you are, I de-identify this Dicom.
[black.dcm.zip](https://github.com/cornerstonejs/cornerstone/files/4018790/black.dcm.zip)

**Comment by dannyrb** [comment]
Hmm.. No slope or intercept value.

![image](https://user-images.githubusercontent.com/5797588/71727860-92c21e00-2e09-11ea-9d0f-3e2160c744a4.png)

It does appear as expected in RadiAnt

**Comment by drozdzynski** [comment]
Any idea how to solve this problem?

**Comment by drozdzynski** [comment]
I found a solution, in WADO initialize I changed `strict` from `true` to `false`
