### ISSUE TITLE
Non Promises/A+ standard API expected

### ISSUE THREAD

**Issue by nuKs** [cornerstonejs/cornerstone#43]
Hello,

I'm working on an opensource viewer using Orthanc for Osimis at the moment.
Your library is of huge help indeed.

Just a slight note as I can't use the cache mechanism with my $q angular promises.

In the method imageCache#decache(), the .reject() method is called. It is non-standard.
https://github.com/chafey/cornerstone/blob/master/src/imageCache.js#L174

Here are some proposals :
- If you want to invalidate your own image callback (the .then imageCache#putImagePromise), ignoring the processing using a if instead of rejecting the callback could do it.
  https://github.com/chafey/cornerstone/blob/master/src/imageCache.js#L89
- If you want to make sure the user's promise is invalidated, in imageCache#putImagePromise, storing an intermediary .then inside which you throw an exception would work.
  https://github.com/chafey/cornerstone/blob/master/src/imageCache.js#L80

Are you interested in changing this ? Would you like me to submit a patch ?

Thibault Piront.

**Comment by chafey** [comment]
Cornerstone should be promises a+ compliant, I didn't realize that reject() was not part of the standard!  I did some quick looking and am not exactly sure how to do what I want in a compliant way.  I basically need to propagate an error back to the code that has the promise - maybe you can submit a PR showing how you think it would be best to do this so I can see it in action?  If there are in fact multiple ways to do this, help me guide you :)

**Comment by nuKs** [comment]
Glad to help :-)

The only A+ compliant method is the .then,
so if you want to reject a promise and stay compatible, there is two way to do this :
- wrap your promise using a standard promise lib. Using its non-standard methods will still keep the promise standard. This requires indeed to add the promise lib as a dependency.
- throw an exception inside a then. The exception will be catched by any standard promise library and be converted into a promise reject.

I'll submit a pull request with the second solution today.

**Comment by nuKs** [comment]
This should have the same behavior as now :
https://github.com/nuKs/cornerstone/commit/47924689dcfb3de9647b0a2eacbcf9d567b3ed96
I still have to test it.

Not sure about it, but I think it is only usefull when the promise is resolved after the cache has cleaned though. I don't think there is a concrete use case for this as long as the end user doesn't store its promises. Is your intent is to prevent this ?
