### ISSUE TITLE
Rescaling images on two layers

### ISSUE THREAD

**Issue by jwitos** [cornerstonejs/cornerstone#440]
Hi! I'm trying to display two images in layers onto an element. One is loaded through the WADO Loader and has dimensions of eg. 2000x3000 and the other through Web Image Loader and has dimensions of e.g. 500x500. 

Browsing through the API, I noticed [rescaleImage()](https://docs.cornerstonejs.org/api.html#rescaleimage) and tried to use it. Initially, trying to use it as `cornerstone.rescaleImage(layer1, layer2)` returned `cornerstone.rescaleImage is not a function`. After adding it to exports I was able to call it but it doesn't really match layers dimensions as I expected.

Is that the proper usage of `rescaleImage()`? If I understand correctly, the best (only?) way to match two images would be a custom image loader that rescales the images in there?

Thanks!

**Comment by jwitos** [comment]
Alright, I understand how it works now. Images loaded through the WADO have their own pixel spacing, unlike WebImageLoader images which have spacing of `undefined`. That resulted in situation where even if they had the same pixel dimensions, their viewports were scaled differently.

Adding `columnPixelSpacing` and `rowPixelSpacing` properties to image loaded from cornerstoneWebImageLoader solved the issue. Not sure if that's the most optimal solution but works!

**Comment by desprit** [comment]
In my case it was a little bit different. I'm rendering a SEG dicom on top of the normal one. I tried to manually change scale and pixel spacing on both of them bit it didn't work - the SEG dicom always had different scale.
Then I changed it's originalScale and it worked!
```
layers[i].syncProps.originalScale = layers[0].viewport.scale;
```

**Comment by CredoSpero** [comment]
> Hi! I'm trying to display two images in layers onto an element. One is loaded through the WADO Loader and has dimensions of eg. 2000x3000 and the other through Web Image Loader and has dimensions of e.g. 500x500.
> 
> Browsing through the API, I noticed [rescaleImage()](https://docs.cornerstonejs.org/api.html#rescaleimage) and tried to use it. Initially, trying to use it as `cornerstone.rescaleImage(layer1, layer2)` returned `cornerstone.rescaleImage is not a function`. After adding it to exports I was able to call it but it doesn't really match layers dimensions as I expected.
> 
> Is that the proper usage of `rescaleImage()`? If I understand correctly, the best (only?) way to match two images would be a custom image loader that rescales the images in there?
> 
> Thanks!

Hi! I am also trying to display two images in layers onto an element. One of which is loaded through WADO and the other is through Web, exactly the same as @jwitos. Similarly, I run into the same issue where it returns "cornerstone.rescaleImage is not a function". I have also tried adding columnPixelSpacing and rowPixelSpacing properties to image loaded from cornerstoneWebImageLoader in hopes to solve the issue but the function still does not run. Could I clarify how did you manage to get the function to run and what do you mean by adding to exports? Would really appreciate if you could show a snapshot of the code, that would help greatly as I am not very experience in this area. Thank you!

**Comment by CredoSpero** [comment]
> Hi @CredoSpero, unfortunately I don't have access to that code and I haven't used cornerstonejs in a while, sorry... Maybe one of the cornerstone devs will be able to help here, it's probably best if you open a new issue with your code and link to this one as a reference?

Okay thank you so much for the quick response. Will open a new issue instead!
