### ISSUE TITLE
Issue reading WW/WC value in multi frame studies

### ISSUE THREAD

**Issue by triet12369** [cornerstonejs/cornerstone#443]
Hi guys,
Today we encountered a strange study from our modality (MRI - Philips Prodiva 1.5T). When opening it with Osimis viewer or MedDream, the WW/WC value displayed on the Web viewer is different compared to Radiant. 

Here's the detailed behavior, taken from the 1st image of series SURVEY :
1. Osimis: WW/WC is 1431/720
![image](https://user-images.githubusercontent.com/17722668/75658427-e67ea580-5c9a-11ea-8854-8e69133c049c.png)
2. MedDream: WW/WC is 1447/724
![image](https://user-images.githubusercontent.com/17722668/75658601-33627c00-5c9b-11ea-8bbf-8d8b7b01c3bb.png)
3. Radiant: WW/WC is 1628/937
![image](https://user-images.githubusercontent.com/17722668/75658652-45dcb580-5c9b-11ea-8dde-bfb4ce0e8c51.png)

Upon further tag inspection, I found out that this study is multiframe and it's image metadata is stored in the tag **(5200,9230)(PerFrameFunctionalGroupsSequence)**
![image](https://user-images.githubusercontent.com/17722668/75658925-b7b4ff00-5c9b-11ea-89a4-e75b49e25044.png)

From this tag, it appears that the reading in Radiant is correct. Can Cornerstone handle multiframe studies like in Radiant? Is there any way to solve this problem? 
Thank you for your time.

Attached study:
[ERROR_METADATA.zip](https://github.com/cornerstonejs/cornerstone/files/4274190/ERROR_METADATA.zip)
View online: https://www.dicomlibrary.com?study=1.2.826.0.1.3680043.8.1055.1.2020030292322251.187856257.98617819

**Comment by dannyrb** [comment]
The width/center is set on the created "Cornerstone Image" in a Cornerstone Image Loader:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L146-L151

This is likely where you would need to add support for this use case. You may want to consider opening a similar issue in that same repository.
