### ISSUE TITLE
One canvas, two layers, different sources and sizes

### ISSUE THREAD

**Issue by jwitos** [cornerstonejs/cornerstone#445]
Hi there!
I have trouble properly loading two images (layers) into my canvas.

My first layer is loaded through WADOImageLoader and creates a layer with `cornerstone.addLayer`. This creates a layer with image of e.g. height=2000, width=3000 and a canvas of height=2000 and width=3000.

I would like to load raw RGBA pixel values as another layer. I created a custom imageLoader [based on your colorImage example](https://rawgit.com/cornerstonejs/cornerstone/master/example/colorImage/index.html) and registered it.

Pixel values coming through the RGBA pixel loader have different sizes, e.g. 400x500. I would like to resize them to the original canvas size (in this example:2000x3000) so that they overlay the first layer. This is where I am stuck.

I am able to load the image in it's original size and put it as another layer, but I can't get to scale it. I can scale the whole canvas with e.g.:

    const activeLayer = cornerstone.getActiveLayer(element);
    const canvas = activeLayer.canvas;
    const canvasContext = canvas.getContext('2d');
    canvasContext.putImageData(imageData, 0, 0);
    canvasContext.scale(2.0,2.0);

But it scales both layers.

Is there a way to resize the image on a single layer or should I rather look into e.g. interpolation of pixel array to designated size?

Sorry for the complicated case -- I'm not really used to Canvas concepts.

**Comment by dannyrb** [comment]
This is not something I'm super familiar with, but hopefully this helps:

Cornerstone has a "viewport", but I believe all layers share the viewport (note the `scale` property).

https://github.com/cornerstonejs/cornerstone/blob/12da9ed267499345ef192d9e5f214cc79122ffc3/src/internal/getDefaultViewport.js#L10-L34

It looks like each layer may also have a "viewport", and if you configure things properly, you can scale it independently:

https://github.com/cornerstonejs/cornerstone/blob/12da9ed267499345ef192d9e5f214cc79122ffc3/src/layers.js#L79-L124

With, I think, the structure looking something like this:

- Enabled Element
  - Has: Viewport
  - Has: Layers
    - Has: Viewport

**Comment by jwitos** [comment]
Thanks @dannyrb, this was really helpful. I've almost completely solved my problem. The workflow that worked for me was:

1. Load the DICOM through WADOImageLoader and add first `Layer`.
2. Create an image loader for RGBA pixels [based on the color image example](https://rawgit.com/cornerstonejs/cornerstone/master/example/colorImage/index.html).
3. Load `Image` through the new RGBA loader
4. Set pixel spacing in new `Image` equal to the first one (from WADO)
5. Add second `Layer` with new `Image`:
```
rgba_layer = cornerstone.addLayer(element, image)
```
6. Set second Layer as active:
```
cornerstone.setActiveLayer(element, rgba_layer);
```
7. Un-sync viewports between layers:

```
var enabledElement = cornerstone.getEnabledElement(element);
enabledElement.syncViewports = false;
cornerstone.updateImage(element);
```

8. Compute ratio to rescale viewport on new layer. Something like: `canvas width`/`new image width`*`viewport scale on first layer`
9. Change viewport on the second Layer:

```
let viewport = cornerstone.getViewport(element);
viewport.scale = ratio;
cornerstone.setViewport(element,viewport);
```

[The "layers" example](https://rawgit.com/cornerstonejs/cornerstone/master/example/layers/index.html) was also pretty helpful here.

---

I still have a little problem: when I load the RGBA array it's being drawn "twice". It's shown on a first layer in top-left corner. Kinda like it's being drawn directly into the canvas. Unfortunately I don't have a simple reproducible example to share yet. If that's OK I will keep this issue open for a day longer and try to figure out this problem.

**Comment by jwitos** [comment]
>I still have a little problem: when I load the RGBA array it's being drawn "twice". It's shown on a first layer in top-left corner. Kinda like it's being drawn directly into the canvas. Unfortunately I don't have a simple reproducible example to share yet. If that's OK I will keep this issue open for a day longer and try to figure out this problem.

My bad! I was trying to write the RGBA values (`canvasContext.putImageData(myRgbaPixelData)`) into the original canvas. I thought that the canvas is somehow shared between multiple layers. Turns out that each layer kinda has its own canvas. Thanks again @dannyrb !
