### ISSUE TITLE
Scroll will not render image in div. images get cut.

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstone#452]
Hi,

I am trying to display the images on the ios device first images display perfectly but when I try to apply scroll event and try to render the another images then it will not render the image perfectly. 
but when I click on the reset button **cornerstone.reset(element)** image will be display perfectly. I dont understant whats going wrong with this. 
here I am sharing the code

```
<div class="image-canvas-wrapper">
	<div id="dicomImage" class="cornerstone-element"></div>
</div>
```
<img width="354" alt="Screen Shot 2020-04-21 at 9 56 23 AM" src="https://user-images.githubusercontent.com/2580866/79825949-09365c00-83b8-11ea-9d8a-a7569efecd8c.png">

but when I click the reset button it will display 

<img width="364" alt="Screen Shot 2020-04-21 at 10 09 31 AM" src="https://user-images.githubusercontent.com/2580866/79826019-38e56400-83b8-11ea-9040-e83fcf8e56b5.png">

css
.image-canvas-wrapper {
  width: 512px;
  height: 325px;
  margin: 35px auto;
  background: black;
}

.cornerstone-element {
  width: 100%;
  height: 100%;
}
please advice. Thanks for help in advance

**Comment by dannyrb** [comment]
@pmd23, are you able to provide a minimal reproduction? Ideally something that has only the bare minimum code required to reproduce this issue?

Also, this may be better suited for the `cornerstone-tools` repository, or... OHIF, if you're making modifications to it.

**Comment by pmd23** [comment]
ok @dannyrb. i have already posted question @`cornerstone-tools` repository 

[https://github.com/cornerstonejs/cornerstoneTools/issues/1135](url)
please have a look

**Comment by dannyrb** [comment]
@pmd23, ah. No need to open duplicate issues then. Roughly the same group of people monitor all of the cornerstone repositories. If you're having issues receiving a response, it can be helpful to add more information to your question or, in a pinch, seek out paid consulting services.
