### ISSUE TITLE
some special dcm files cannot be displayed normally

### ISSUE THREAD

**Issue by wmxj** [cornerstonejs/cornerstone#454]
**Erik deleted this file because it contained PHI. DO NOT POST PHI**

**Comment by swederik** [comment]
This file has no pixel data. The image you see in other viewers is coming from the Group 6000 Overlay Plane metadata. Your file loads fine here: https://viewer-dev.ohif.org/local

This will display fine if you enable the OverlayTool in Cornerstone Tools: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/OverlayTool.js

**Comment by wmxj** [comment]
thank you very much.
