### ISSUE TITLE
 Dicom file not rendering correctly, for sop class 1.2.840.10008.5.1.1.30 HC Modality

### ISSUE THREAD

**Issue by pmd23** [cornerstonejs/cornerstone#458]
Hi Team,
I working on dicom viewer in which there is some retired tag. I am really new to dicom viewer stuff. I have 1 dcm image with  SOP claass `'1.2.840.10008.5.1.1.30':'Hardcopy Color Image Storage SOP Class (Retired)'` in the some dicom viewer its showing correctly but while trying to load it using cornerstone its shows me weird. **this is HC Modality**
for this image i am getting `image.color = true`.
<img width="1168" alt="upload" src="https://user-images.githubusercontent.com/2580866/81384401-3fe9d180-912f-11ea-9874-f19143cbbcc9.png">
 
My question is that how can i render it so that it will be render as correctly.

**Comment by pmd23** [comment]
any reply on this?

**Comment by cfdongkk** [comment]
get the same problem

**Comment by chafey** [comment]
Can you provide the file?  Hard to debug without it

**Comment by pmd23** [comment]
> Can you provide the file? Hard to debug without it

https://www.dicomlibrary.com?requestType=WADO&studyUID=1.2.826.0.1.3680043.8.1055.1.20200513163033725.451389301.7139177&manage=89ba526b00cb14ee54f6d91af69fe1d1&token=bd12df220bd18cdcf3f804f25e654e5c

**Comment by pmd23** [comment]
[89ba526b00cb14ee54f6d91af69fe1d1.zip](https://github.com/cornerstonejs/cornerstone/files/4621486/89ba526b00cb14ee54f6d91af69fe1d1.zip)

now you can get the file from this zip file

> Can you provide the file? Hard to debug without it

**Comment by pmd23** [comment]
@chafey and @cfdongkk any clue on this?

**Comment by dannyrb** [comment]
Sorry, I don't have the time available I'd need to dig into this. If this is a blocker for you, you can always reach out to a consultant or consultancy.

In the meantime, hopefully someone with the availability and expertise will take a look or provide guidance.

**Comment by pmd23** [comment]
@chafey please any update on this

**Comment by dannyrb** [comment]
@pmd23 tasks like this can be quite time intensive, and most of us are either volunteering our time or doing work on behalf of one or more clients.

Unfortunately, it may be some time before your issue is addressed. Thank you for taking the time to report it, and for providing enough information to help others 👍

**Comment by pmd23** [comment]
server side I have change the transfer Syntax of HC modality. now its working fine.
