### ISSUE TITLE
Deprecate rowPixelSpacing and columnPixelSpacing, add aspect ratio

### ISSUE THREAD

**Issue by chafey** [cornerstonejs/cornerstone#47]
This will avoid confusion related to pixel spacing issues yet preserve non square pixel support in cornerstone core.  CornerstoneTools should be updated to get the pixel spacing via a metadata provider.  @swederik

**Comment by dannyrb** [comment]
@swederik, don't most tools use pixel spacing and related fields from a metaDataProvider when/where applicable? Can this be closed?

**Comment by swederik** [comment]
Yeah looks like we can close this
