### ISSUE TITLE
How to load overlay display of two DCM files on canvas

### ISSUE THREAD

**Issue by JerryGit1** [cornerstonejs/cornerstone#471]
Hello, the cornerstone is really great. At present, we need to load the overlay display of two DCM files on the canvas. Then adjust the color and transparency separately. Is there any way to do this?

example（superposition）:

![image](https://user-images.githubusercontent.com/34857855/87929750-7f328800-cab9-11ea-99aa-ed640f97c0f7.png)

**Comment by Lichking1** [comment]
I have faced the similar issue, I tried several ways to resolve:
1: Directly overlay 2 html div, which is a pretty hack ways to solve, but this will result in the display in the bottom become dim when increase opacity on the top, and I tried to use viewport.colormap to change the color but unable to change the color(I am still working on that). 
2: https://rawgit.com/chafey/cornerstone/master/example/layers/index.html I tried using layers to display, but two dcm files have a lot of slices, which is hard to achieve synchronization using cornerstone-tools...

**Comment by JerryGit1** [comment]
> I have faced the similar issue, I tried several ways to resolve:
> 1: Directly overlay 2 html div, which is a pretty hack ways to solve, but this will result in the display in the bottom become dim when increase opacity on the top, and I tried to use viewport.colormap to change the color but unable to change the color(I am still working on that).
> 2: https://rawgit.com/chafey/cornerstone/master/example/layers/index.html I tried using layers to display, but two dcm files have a lot of slices, which is hard to achieve synchronization using cornerstone-tools...

Wow, that's great. Thank you for your plan, which has made a great breakthrough in my work. I'm going to use the second method. Thanks again
