### ISSUE TITLE
Unable to disable smoothing

### ISSUE THREAD

**Issue by hakkelt** [cornerstonejs/cornerstone#613]
As far as I understood, it was possible in the previous versions to turn off the native canvas interpolation/smoothing by changing the "pixelReplication" value on the viewport, but it seems to be no longer supported (at least, I could not find the way in the documentation).

Is it possible somehow to disable smoothing? I would like to use cornerstone to develop an application for viewing MR images of mice and rats. The resolution of the images is usually relatively low, and displaying with native resolution is frequently not desirable.

**Comment by No-Dream-No-Life** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，邮件我已收到，我将在看到后第一时间给您回复。
