### ISSUE TITLE
How to use internals

### ISSUE THREAD

**Issue by iberisoft** [cornerstonejs/cornerstone#624]
I am sorry for probably a stupid question, I am not very experienced with JS. How may I call the internal functions https://docs.cornerstonejs.org/api.html#internal? For example, `getImageFitScale`. Thank you!

**Comment by No-Dream-No-Life** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，邮件我已收到，我将在看到后第一时间给您回复。
