### ISSUE TITLE
webgl branch: performance improvement for WL

### ISSUE THREAD

**Issue by mdg583** [cornerstonejs/cornerstone#69]
Hi,
I'm trying out cornerstone-webgl (actually OHIF) for a test viewer for a DICOM store of X-Rays. I had a problem that the performance was quite bad. This is because the X-Ray images we have are of a size 4248x3480. The webGL render with the shaders seemed to be fast (good fps), but there was a bad lag in user interaction.

Eventually I found out that in a simple test of a webl canvas of size 4248x3480, even running just glClear on the canvas as the user moves the mouse led to pretty bad performance. So I decided to try to change the way the webgl renders, so that the webgl canvas is of the same size as the enabled canvas, and the view transform happens in the vertex shader.

It worked, and here are the changes I made.
[cornerstone_webgl.patch.txt](https://github.com/chafey/cornerstone/files/375946/cornerstone_webgl.patch.txt)

In OHIF, I also needed to make one change in imageViewerViewport.js, I'm guessing because OHIF has a slightly older version of cornerstone in it

```
--- imageViewerViewport.orig.js 2016-07-21 13:41:05.775327411 +0300
+++ imageViewerViewport.js  2016-07-21 13:11:34.248607304 +0300
@@ -124,7 +124,7 @@
     // NOTE: This uses the experimental WebGL renderer for Cornerstone!
     // If you have problems, replace it with this line instead:
     // cornerstone.enable(element);
-    cornerstone.enable(element, cornerstone.webgl.renderer.render);
+    cornerstone.enable(element, {renderer: 'webgl'});

     // Get the handler functions that will run when loading has finished or thrown
     // an error. These are used to show/hide loading / error text boxes on each viewport.
```

However this still doesn't work on a number of PCs, because the texture is so big. I'm not sure if something like a texture array would help with this.

**Comment by swederik** [comment]
Hmm very interesting. I hadn't encountered any performance issues with the WebGL branch but I am interested to test out these changes. Thanks for the patch!

**Comment by mdg583** [comment]
No problem... I tried out the idea of creating an array of textures, making a grid of texture of size for example 1024x1024, depending on what the client reports for gl.MAX_TEXTURE_SIZE. It seems to work. But needs some more work. But for some of these old PCs, they seem to run in to memory problems -after opening a few images, things seem to bog down. In some cases Chrome said that webgl had failed and the page should be loaded again - and cornerstone reverted to non-webgl canvas.

**Comment by mdg583** [comment]
Here is what I tried for an array of textures. Not sure what the quality of the code is. I don't know why there is a white line on the right + bottom edge of the images at some zoom levels. I tried fixing that but it didn't work out.

[texArray.patch.txt](https://github.com/chafey/cornerstone/files/381521/texArray.patch.txt)

**Comment by mdg583** [comment]
The texArray patch introduces a bug, since gl is undefined in textureCache. Hopefully this is better
[corenerstone_update.patch.txt](https://github.com/chafey/cornerstone/files/476367/corenerstone_update.patch.txt)

**Comment by swederik** [comment]
Hey,

Sorry I still haven't managed to find time to look into this. Thanks for the additional fixes though.

**Comment by matthiasg** [comment]
@mdg583  nice work so far. you might want to clone this project and submit a pull request, it gets easier to follow your changes and comment on it.

we implemented a tiling mechanism for our own renderers back in the day as one way to solve the issue, but in order to improve memory mechanics we let the renderer reserve the tiles for the lifetime of the view and reused it for all images (only reallocating when the current image did not fit inside the available tiles).

I haven't looked deeply into your patch though, maybe you are already doing something like that.

**Comment by mdg583** [comment]
Hi Matthias,

Actually I didn't implement any kind of texture reservation as I 
remember, I just try to free and reallocate the texture tiles.

I don't have much experience with graphics or opengl, I was basically 
just focused on what would work for the specific place I was looking to 
use OHIF, which was a small hospital for chest diseases which basically 
only manages chest x-rays. But I am not based at that location any 
longer, and don't have a test machine, so I don't think I can work on 
this very well for the time being.

Have a good day,

Matthew

**Comment by dannyrb** [comment]
This issue is creeping up on > 3 years old. Personally, I have not encountered WebGL performance issues. If someone feels this is still a good candidate for optimization/improvement, it would be best to create a new issue for discussion along with any ideas/suggestions you may have.

**Comment by mdg583** [comment]
Hi dannyrb,
That sounds good. At the facility where I first tried this, we also
reverted to using the standard version and don't have performance issues
anymore.
Matthew
