### ISSUE TITLE
Is there a way to pan a zoomed image, so we can only explore in the image (and not drag the image off the screen)?

### ISSUE THREAD

**Issue by gituser7878-Ultralinq** [cornerstonejs/cornerstone#87]
Right now I am using cornerstoneTools.pan.activate(cornerstoneEnabledElement, 1) and getting behavior like this -
https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html (use the zoom feature and then the pan feature to see what I mean - we can effectively drag the whole image out of view in the pan feature).

I would like to be able to have behavior like this - http://jsfiddle.net/CqcHD/2/
where we can only pan within the bounds of the image and never go outside the image.

How would I implement such behavior with cornerstone? Would that jsfiddle-type code, work with a cornerstone enabled element that has mouse input enabled via cornerstone?

**Comment by dannyrb** [comment]
I don't believe that this makes sense as an enhancement for cornerstone. If you take a peak at the code for how panning is handled in cornerstoneTools, you'll see that you're:

- Finding the deltaX and deltaY as the mouse is clicked and dragged.
- As you're dragging, that you apply the deltaX and deltaY to the following viewport properties:
    - `viewport.translation.x`
    - `viewport.translation.y`
- Lastly, you update the viewport by calling: `cornerstone.setViewport(element, viewport);`

As you have complete control over the translation, you can implement your own bounds for the image. For example, if you track:

- The coordinates for each corner of your image
- The dimensions of your canvas

You can add logic to test for collision / barriers as you pan or zoom, and snap to your barrier's constraints.

IE.
- onPanning
- if my deltaX is negative (moving left) AND
- if my image's bottom right corner's X coordinate is less than my canvas's width
- do not update the viewer's viewport

**Comment by swederik** [comment]
I would agree with @dannyrb. I think the best option would be for you to create a separate tool which clones Pan and just adds some restrictions.

See https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/imageTools/pan.js#L47
